---select * from a2_GeneProperty

REM INSERTING into A2_GENEPROPERTY
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (1,'CAS','AE2__GENE_CAS__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (2,'CHEBI','AE2__GENE_CHEBI__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (3,'CHEMFORMULA','AE2__GENE_CHEMFORMULA__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (4,'DBXREF','AE2__GENE_DBXREF__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (5,'DESC','AE2__GENE_DESC__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (6,'DISEASE','AE2__GENE_DISEASE__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (7,'EMBL','AE2__GENE_EMBL__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (8,'ENSFAMILY','AE2__GENE_ENSFAMILY__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (9,'ENSGENE','AE2__GENE_ENSGENE__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (10,'ENSPROTEIN','AE2__GENE_ENSPROTEIN__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (11,'ENSTRANSCRIPT','AE2__GENE_ENSTRANSCRIPT__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (12,'GOTERM','AE2__GENE_GOTERM__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (13,'GO','AE2__GENE_GO__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (14,'HMDB','AE2__GENE_HMDB__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (15,'IDS','AE2__GENE_IDS__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (16,'IMAGE','AE2__GENE_IMAGE__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (17,'INTERPROTERM','AE2__GENE_INTERPROTERM__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (18,'INTERPRO','AE2__GENE_INTERPRO__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (19,'KEYWORD','AE2__GENE_KEYWORD__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (20,'LOCUSLINK','AE2__GENE_LOCUSLINK__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (21,'OMIM','AE2__GENE_OMIM__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (22,'ORF','AE2__GENE_ORF__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (23,'ORTHOLOG','AE2__GENE_ORTHOLOG__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (24,'PATHWAY','AE2__GENE_PATHWAY__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (25,'PROTEINNAME','AE2__GENE_PROTEINNAME__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (26,'REFSEQ','AE2__GENE_REFSEQ__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (27,'SYNONYM','AE2__GENE_SYNONYM__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (28,'UNIGENE','AE2__GENE_UNIGENE__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (29,'UNIPROTMETENZ','AE2__GENE_UNIPROTMETENZ__DM');
Insert into A2_GENEPROPERTY (GENEPROPERTYID,NAME,AE2TABLENAME) values (30,'UNIPROT','AE2__GENE_UNIPROT__DM');

COMMIT WORK;