
begin
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 124,'PROP-1','','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 1,'RNAi','AE1__ASSAY_RNAI__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 2,'age','AE1__ASSAY_AGE__DM','AE1__SAMPLE_AGE__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 3,'cellline','AE1__ASSAY_CELLLINE__DM','AE1__SAMPLE_CELLLINE__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 4,'celltype','AE1__ASSAY_CELLTYPE__DM','AE1__SAMPLE_CELLTYPE__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 5,'clinhistory','AE1__ASSAY_CLINHISTORY__DM','AE1__SAMPLE_CLINHISTORY__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 6,'clininfo','AE1__ASSAY_CLININFO__DM','AE1__SAMPLE_CLININFO__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 7,'clintreatment','AE1__ASSAY_CLINTREATMENT__DM','AE1__SAMPLE_CLINTREATMENT__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 8,'compound','AE1__ASSAY_COMPOUND__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 9,'devstage','AE1__ASSAY_DEVSTAGE__DM','AE1__SAMPLE_DEVSTAGE__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 10,'diseaselocation','','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 11,'diseasestaging','AE1__ASSAY_DISEASESTAGING__DM','AE1__SAMPLE_DISEASESTAGING__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 12,'diseasestate','AE1__ASSAY_DISEASESTATE__DM','AE1__SAMPLE_DISEASESTATE__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 13,'dose','AE1__ASSAY_DOSE__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 14,'ecotype','AE1__ASSAY_ECOTYPE__DM','AE1__SAMPLE_ECOTYPE__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 15,'genmodif','AE1__ASSAY_GENMODIF__DM','AE1__SAMPLE_GENMODIF__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 16,'genotype','AE1__ASSAY_GENOTYPE__DM','AE1__SAMPLE_GENOTYPE__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 17,'growthcondition','AE1__ASSAY_GROWTHCONDITION__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 18,'histology','AE1__ASSAY_HISTOLOGY__DM','AE1__SAMPLE_HISTOLOGY__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 19,'indgeneticchar','AE1__ASSAY_INDGENETICCHAR__DM','AE1__SAMPLE_INDGENETICCHAR__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 20,'individual','AE1__ASSAY_INDIVIDUAL__DM','AE1__SAMPLE_INDIVIDUAL__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 21,'infect','AE1__ASSAY_INFECT__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 22,'injury','AE1__ASSAY_INJURY__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 23,'light','AE1__ASSAY_LIGHT__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 24,'materialType','AE1__ASSAY_MATERIALTYPE__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 25,'media','AE1__ASSAY_MEDIA__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 26,'observation','AE1__ASSAY_OBSERVATION__DM','AE1__SAMPLE_OBSERVATION__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 27,'organism','AE1__ASSAY_ORGANISM__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 28,'organismpart','AE1__ASSAY_ORGANISMPART__DM','AE1__SAMPLE_ORGANISMPART__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 29,'phenotype','AE1__ASSAY_PHENOTYPE__DM','AE1__SAMPLE_PHENOTYPE__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 30,'protocoltype','AE1__ASSAY_PROTOCOLTYPE__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 31,'replicate','AE1__ASSAY_REPLICATE__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 32,'sex','AE1__ASSAY_SEX__DM','AE1__SAMPLE_SEX__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 33,'strainorline','AE1__ASSAY_STRAINORLINE__DM','AE1__SAMPLE_STRAINORLINE__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 34,'targetcelltype','AE1__ASSAY_TARGETCELLTYPE__DM','AE1__SAMPLE_TARGETCELLTYPE__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 35,'temperature','AE1__ASSAY_TEMPERATURE__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 36,'testresult','AE1__ASSAY_TESTRESULT__DM','AE1__SAMPLE_TESTRESULT__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 37,'time','AE1__ASSAY_TIME__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 38,'tumorgrading','AE1__ASSAY_TUMORGRADING__DM','AE1__SAMPLE_TUMORGRADING__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 39,'vehicle','AE1__ASSAY_VEHICLE__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 104,'BIOMETRIC','AE1__ASSAY_BIOMETRIC__DM','AE1__SAMPLE_BIOMETRIC__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 105,'CULTIVAR','AE1__ASSAY_CULTIVAR__DM','AE1__SAMPLE_CULTIVAR__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 106,'DISEASELOC','AE1__ASSAY_DISEASELOC__DM','AE1__SAMPLE_DISEASELOC__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 107,'ENVHISTORY','AE1__ASSAY_ENVHISTORY__DM','AE1__SAMPLE_ENVHISTORY__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 108,'FAMILYHISTORY','AE1__ASSAY_FAMILYHISTORY__DM','AE1__SAMPLE_FAMILYHISTORY__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 109,'GENERATION','AE1__ASSAY_GENERATION__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 110,'INITIALTIME','AE1__ASSAY_INITIALTIME__DM','AE1__SAMPLE_INITIALTIME__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 111,'ORGANISMSTATUS','AE1__ASSAY_ORGANISMSTATUS__DM','AE1__SAMPLE_ORGANISMSTATUS__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 112,'PERFORMER','AE1__ASSAY_PERFORMER__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 113,'POPULATION','AE1__ASSAY_POPULATION__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 114,'QCDESCRTYPE','AE1__ASSAY_QCDESCRTYPE__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 115,'SOURCEPROVIDER','AE1__ASSAY_SOURCEPROVIDER__DM','AE1__SAMPLE_SOURCEPROVIDER__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 116,'TESTTYPE','AE1__ASSAY_TESTTYPE__DM','AE1__SAMPLE_TESTTYPE__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 117,'TEST','AE1__ASSAY_TEST__DM','' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 118,'ALL','','AE1__SAMPLE_ALL__DM' from dual; 
Insert into a2_property (PropertyID,Name,AE1TABLENAME_ASSAY,AE1TABLENAME_SAMPLE) select 119,'TEST_','','AE1__SAMPLE_TEST__DM' from dual; 

end;
/
COMMIT WORK;
/
