SET SERVEROUT ON SIZE 1000000;
/

DECLARE
  EXPERIMENTID NUMBER;
  ARRAYDESIGNID NUMBER;
  ASSAYS AtlasAPI.CurExpressionValueAssay;
  DESIGNELEMENTS AtlasAPI.CurExpressionValueDE;
  EXPRESSIONVALUES AtlasAPI.CurExpressionValues;
  
  ASSAY ASSAYS%ROWTYPE;
  DESIGNELEMENT DESIGNELEMENTS%ROWTYPE;
  EXPRESSIONVALUE EXPRESSIONVALUES%ROWTYPE;
BEGIN
  EXPERIMENTID := 1261;
  ARRAYDESIGNID := 130297520;

  ATLASAPI.A2_EXPRESSIONVALUEGET(
    EXPERIMENTID => EXPERIMENTID,
    ARRAYDESIGNID => ARRAYDESIGNID,
    ASSAYS => ASSAYS,
    DESIGNELEMENTS => DESIGNELEMENTS,
    EXPRESSIONVALUES => EXPRESSIONVALUES
  );

LOOP FETCH ASSAYS INTO ASSAY;
  EXIT WHEN ASSAYS%NOTFOUND;

  DBMS_OUTPUT.put_line('ASSAY:' || TO_CHAR(ASSAY.ASSAYID));
END LOOP;
CLOSE ASSAYS; 

LOOP FETCH DESIGNELEMENTS INTO DESIGNELEMENT;
  EXIT WHEN DESIGNELEMENTS%NOTFOUND;

  --DBMS_OUTPUT.put_line('DESIGNELEMENT:' || TO_CHAR(DESIGNELEMENT.DesignElementID));
  DBMS_OUTPUT.put_line('+');
END LOOP;
CLOSE DESIGNELEMENTS; 

LOOP FETCH EXPRESSIONVALUES INTO EXPRESSIONVALUE;
  EXIT WHEN EXPRESSIONVALUES%NOTFOUND;

  --DBMS_OUTPUT.put_line('Value:' || TO_CHAR(EXPRESSIONVALUE.Value));
  DBMS_OUTPUT.put_line('v');
END LOOP;
CLOSE EXPRESSIONVALUES;

END;


--select to_char(123) from dual;

/*
select * from a2_assay 
join a2_expressionvalue ev on ev.assayid = a2_assay.assayid
where rownum < 10

where EXPERIMENTID = 1241 and ARRAYDESIGNID = 130297520;
*/
