-- Estimated running time: 30  seconds

ALTER TABLE "A2_ASSAYPVONTOLOGY" DROP CONSTRAINT "PK_ASSAYPVONTOLOGY";

DROP INDEX "IDX_ASSAYPVONTOLOGY_ASSAYPV";

DROP INDEX "IDX_ASSAYPVONTOLOGY_TERM";

ALTER TABLE "A2_ASSAYPVONTOLOGY" DROP CONSTRAINT "UQ_ASSAYPVONTOLOGY";

DROP TRIGGER A2_ASSAYPVONTOLOGY_INSERT;

DROP SEQUENCE "A2_ASSAYPVONTOLOGY_SEQ";

ALTER TABLE "A2_ASSAYPVONTOLOGY" DROP COLUMN "ASSAYPVONTOLOGYID";

ALTER TABLE "A2_ASSAYPVONTOLOGY" ADD CONSTRAINT "PK_ASSAYPVONTOLOGY"
    PRIMARY KEY ("ONTOLOGYTERMID", "ASSAYPVID")
    /*PK_TABLESPACE*/
    ENABLE;


ALTER TABLE "A2_SAMPLEPVONTOLOGY" DROP CONSTRAINT "PK_SAMPLEPVONTOLOGY";

DROP INDEX "IDX_SAMPLEPVONTOLOGY_SAMPLEPV";

DROP INDEX "IDX_SAMPLEPVONTOLOGY_ONTOLOGY";

ALTER TABLE "A2_SAMPLEPVONTOLOGY" DROP CONSTRAINT "UQ_SAMPLEPVONTOLOGY";

DROP TRIGGER A2_SAMPLEPVONTOLOGY_INSERT;

DROP SEQUENCE "A2_SAMPLEPVONTOLOGY_SEQ";

ALTER TABLE "A2_SAMPLEPVONTOLOGY" DROP COLUMN "SAMPLEPVONTOLOGYID";

ALTER TABLE "A2_SAMPLEPVONTOLOGY" ADD CONSTRAINT "PK_SAMPLEPVONTOLOGY"
    PRIMARY KEY ("ONTOLOGYTERMID", "SAMPLEPVID")
    /*PK_TABLESPACE*/
    ENABLE;
    

-- Will be done by script runner from the next version on
insert into A2_SCHEMACHANGES values (null, '20110811-1-proper_associations.sql', 'alf', CURRENT_TIMESTAMP);