CREATE INDEX "IDX_BIOENTITYBEPV_ASSOCIATION"
  ON "A2_BIOENTITYBEPV" (BIOENTITYID, SOFTWAREID, bepropertyvalueid)
  /*INDEX_TABLESPACE*/;

CREATE INDEX "IDX_DESIGNELTBIOENTITY_ASS"
  ON A2_DESIGNELTBIOENTITY (DESIGNELEMENTID, BIOENTITYID)
  /*INDEX_TABLESPACE*/;

CREATE INDEX "IDX_ARRAYDESIGN_ASS"
  ON A2_ARRAYDESIGN (ARRAYDESIGNID, MAPPINGSWID)
  /*INDEX_TABLESPACE*/;

DROP INDEX "IDX_BIOENTITYBEPV_BIOENTITY";