-- AnnotationSource table
CREATE SEQUENCE  A2_ANNOTATIONSRC_SEQ
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;

CREATE TABLE A2_ANNOTATIONSRC(
  annotationsrcid NUMBER(22,0)  CONSTRAINT NN_ANNOTATIONSRC_ID NOT NULL
  , SOFTWAREID NUMBER(22,0)  CONSTRAINT NN_ANNOTATIONSRC_SWID NOT NULL
  , ORGANISMID NUMBER(22,0) CONSTRAINT NN_ANNOTATIONSRC_ORGANISM NOT NULL
  , url VARCHAR2(512)
  , biomartorganismname VARCHAR2(255)
  , annsrctype VARCHAR2(255) CONSTRAINT NN_ANNOTATIONSRC_ASTYPE NOT NULL
);

ALTER TABLE A2_ANNOTATIONSRC
  ADD CONSTRAINT PK_ANNOTATIONSRC
    PRIMARY KEY (annotationsrcid)
  ENABLE;

ALTER TABLE A2_ANNOTATIONSRC
  ADD CONSTRAINT FK_ANNOTATIONSRC_ORGANISM
    FOREIGN KEY (ORGANISMID)
    REFERENCES A2_ORGANISM (ORGANISMID);

ALTER TABLE A2_ANNOTATIONSRC
  ADD CONSTRAINT UQ_ANNSRC_NAME_V_ORG_TYPE
    UNIQUE(SOFTWAREID, ANNSRCTYPE, ORGANISMID)
    ENABLE;

ALTER TABLE "A2_ANNOTATIONSRC"
  ADD CONSTRAINT "FK_ANNSRC_SOFTWARE"
    FOREIGN KEY ("SOFTWAREID")
    REFERENCES "A2_SOFTWARE" ("SOFTWAREID")
    ON DELETE CASCADE
    ENABLE;

CREATE OR REPLACE TRIGGER A2_ANNOTATIONSRC_INSERT
before insert on A2_ANNOTATIONSRC
for each row
begin
if(:new.annotationsrcid is null) then
select A2_ANNOTATIONSRC_SEQ.nextval into :new.annotationsrcid from dual;
end if;
END;
/

-- Link table AnnotationSource to Bioentity type
CREATE TABLE A2_ANNSRC_BIOENTITYTYPE(
  annotationsrcid NUMBER(22,0) CONSTRAINT NN_ANNSRCBET_ANNSRCID NOT NULL
  , BIOENTITYTYPEID NUMBER(22,0) CONSTRAINT NN_ANNSRCBET_BETID NOT NULL
  );

ALTER TABLE A2_ANNSRC_BIOENTITYTYPE
  ADD CONSTRAINT UQ_ANNSRCBETYPE_AS_BET
    UNIQUE(annotationsrcid, BIOENTITYTYPEID)
    ENABLE;

ALTER TABLE A2_ANNSRC_BIOENTITYTYPE
  ADD CONSTRAINT FK_A2_ANNSRCBETYPE_BETYPE
    FOREIGN KEY (BIOENTITYTYPEID)
    REFERENCES A2_BIOENTITYTYPE (BIOENTITYTYPEID)
    ON DELETE CASCADE
    ENABLE;

ALTER TABLE A2_ANNSRC_BIOENTITYTYPE
  ADD CONSTRAINT FK_ANNSRCBETYPE_ANNSRC
    FOREIGN KEY (annotationsrcid)
    REFERENCES A2_ANNOTATIONSRC (annotationsrcid)
    ON DELETE CASCADE
    ENABLE;

-- BioMart Property table
CREATE SEQUENCE  A2_BIOMARTPROPERTY_SEQ
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;

CREATE TABLE A2_BIOMARTPROPERTY (
  BIOMARTPROPERTYID NUMBER(22,0) CONSTRAINT NN_BIOMARTPROPERTY_ID NOT NULL
, BIOENTITYPROPERTYID NUMBER(22,0) CONSTRAINT NN_BMPROPERTY_BEPROPERTYID NOT NULL
, NAME VARCHAR2(255) CONSTRAINT NN_BMPROPERTY_NAME NOT NULL
);

ALTER TABLE A2_BIOMARTPROPERTY
  ADD CONSTRAINT PK_BIOMARTPROPERTY
    PRIMARY KEY (BIOMARTPROPERTYID)
    ENABLE;

ALTER TABLE A2_BIOMARTPROPERTY
  ADD CONSTRAINT FK_BIOMARTPROPERTY_PROPERTY
    FOREIGN KEY (BIOENTITYPROPERTYID)
    REFERENCES A2_BIOENTITYPROPERTY (BIOENTITYPROPERTYID)
    ON DELETE CASCADE
    ENABLE;

ALTER TABLE A2_BIOMARTPROPERTY
  ADD CONSTRAINT UQ_BMPROPERTY_BEPROPE_NAME
    UNIQUE(BIOENTITYPROPERTYID, NAME)
    ENABLE;

CREATE OR REPLACE TRIGGER A2_BIOMARTPROPERTY_INSERT
BEFORE INSERT ON A2_BIOMARTPROPERTY
FOR EACH ROW
BEGIN
IF(:NEW.BIOMARTPROPERTYID IS NULL) THEN
SELECT A2_BIOMARTPROPERTY_SEQ.NEXTVAL INTO :NEW.BIOMARTPROPERTYID FROM DUAL;
END IF;
END;
/

-- Link table AnnotationSource to BioMart Property
CREATE TABLE A2_ANNSRC_BIOMARTPROPERTY (
  annotationsrcid NUMBER(22,0) CONSTRAINT NN_ANNSRC2BMPROP_ANNSRCID NOT NULL
  , BIOMARTPROPERTYID NUMBER(22,0) CONSTRAINT NN_ANNSRC2BMPROP_BMPROPID NOT NULL
  );

ALTER TABLE A2_ANNSRC_BIOMARTPROPERTY
  ADD CONSTRAINT UQ_ANNOTATIONSRC_BMPROP
    UNIQUE(annotationsrcid, BIOMARTPROPERTYID)
    ENABLE;

ALTER TABLE A2_ANNSRC_BIOMARTPROPERTY
  ADD CONSTRAINT FK_ANNSRC_BETYPE_BIOMARTPROP
    FOREIGN KEY (BIOMARTPROPERTYID)
    REFERENCES A2_BIOMARTPROPERTY (BIOMARTPROPERTYID)
    ON DELETE CASCADE
    ENABLE;

ALTER TABLE A2_ANNSRC_BIOMARTPROPERTY
  ADD CONSTRAINT FK_ANNSRC_BMPROPERTY_ANNSRC
    FOREIGN KEY (annotationsrcid)
    REFERENCES A2_ANNOTATIONSRC (annotationsrcid)
    ON DELETE CASCADE
    ENABLE;

-- Current AnnotationSource table
CREATE SEQUENCE  A2_CURRENTANNOTATIONSRC_SEQ
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;

CREATE TABLE A2_CURRENTANNOTATIONSRC(
  CURRENTANNOTATIONSRCID NUMBER(22,0)  CONSTRAINT NN_CURRANNSRC_ID NOT NULL
  , ANNOTATIONSRCID NUMBER(22,0)  CONSTRAINT NN_CURRANNSRC_ANNSRC_ID NOT NULL
  , ORGANISMID NUMBER(22,0) CONSTRAINT NN_CURRANNSRC_ORGANISM_ID NOT NULL
  , BIOENTITYTYPEID NUMBER(22,0) CONSTRAINT NN_CURRANNSRC_BETYPEID NOT NULL
  , LOADDATE DATE
  , ANNSRCTYPE VARCHAR2(255) CONSTRAINT NN_CURRANNOTATIONSRC_ASTYPE NOT NULL
);

ALTER TABLE A2_CURRENTANNOTATIONSRC
  ADD CONSTRAINT PK_CURRENTANNOTATIONSRC
    PRIMARY KEY (CURRENTANNOTATIONSRCID)
    ENABLE;

ALTER TABLE A2_CURRENTANNOTATIONSRC
  ADD CONSTRAINT FK_CURRANNOTATIONSRC_BETYPE
    FOREIGN KEY (BIOENTITYTYPEID)
    REFERENCES A2_BIOENTITYTYPE (BIOENTITYTYPEID);

ALTER TABLE A2_CURRENTANNOTATIONSRC
  ADD CONSTRAINT FK_CURRANNSRC_ANNSRC_ID
    FOREIGN KEY (ANNOTATIONSRCID)
    REFERENCES A2_ANNOTATIONSRC (ANNOTATIONSRCID);

ALTER TABLE A2_CURRENTANNOTATIONSRC
  ADD CONSTRAINT FK_CURRANNSRC_ORGANISM_ID
    FOREIGN KEY (ORGANISMID)
    REFERENCES A2_ORGANISM (ORGANISMID);

ALTER TABLE A2_CURRENTANNOTATIONSRC
  ADD CONSTRAINT UQ_CURRANNSRC_ORG_BETYPE
    UNIQUE(ORGANISMID, BIOENTITYTYPEID)
    ENABLE;

CREATE OR REPLACE TRIGGER A2_CURRENTANNOTATIONSRC_INSERT
BEFORE INSERT ON A2_CURRENTANNOTATIONSRC
FOR EACH ROW
BEGIN
IF(:NEW.CURRENTANNOTATIONSRCID IS NULL) THEN
SELECT A2_CURRENTANNOTATIONSRC_SEQ.NEXTVAL INTO :NEW.CURRENTANNOTATIONSRCID FROM DUAL;
END IF;
END;
/
