
  CREATE TABLE "ATLAS2"."A2_ASSAYPROPERTYVALUE" 
   (	"ASSAYPROPERTYVALUEID" NUMBER(22,0) NOT NULL ENABLE, 
	"ASSAYID" NUMBER(22,0), 
	"PROPERTYVALUEID" NUMBER(22,0), 
	"ISFACTORVALUE" NUMBER(22,0), 
	 CONSTRAINT "SYS_C008058" PRIMARY KEY ("ASSAYPROPERTYVALUEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ATLAS2_INDX"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ATLAS2_DATA" ;
 

  CREATE OR REPLACE TRIGGER "ATLAS2"."A2_ASSAYPROPERTYVALUE_INSERT" 
 

before insert on A2_AssayPropertyValue
for each row
begin
if(:new.AssayPropertyValueID is null) then
select A2_AssayPropertyValue_seq.nextval into :new.AssayPropertyValueID from dual;
end if;
end;
/
ALTER TRIGGER "ATLAS2"."A2_ASSAYPROPERTYVALUE_INSERT" ENABLE;
 
