
  CREATE TABLE "ATLAS2"."A2_ASSAY" 
   (	"ASSAYID" NUMBER(22,0) NOT NULL ENABLE, 
	"ACCESSION" VARCHAR2(255 BYTE), 
	"EXPERIMENTID" NUMBER(22,0) NOT NULL ENABLE, 
	"ARRAYDESIGNID" NUMBER(22,0) NOT NULL ENABLE, 
	 CONSTRAINT "SYS_C008055" PRIMARY KEY ("ASSAYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ATLAS2_INDX"  ENABLE, 
	 CONSTRAINT "FKA2_ASSAY856724" FOREIGN KEY ("ARRAYDESIGNID")
	  REFERENCES "ATLAS2"."A2_ARRAYDESIGN" ("ARRAYDESIGNID") ENABLE, 
	 CONSTRAINT "FKA2_ASSAY169476" FOREIGN KEY ("EXPERIMENTID")
	  REFERENCES "ATLAS2"."A2_EXPERIMENT" ("EXPERIMENTID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ATLAS2_DATA" ;
 

  CREATE OR REPLACE TRIGGER "ATLAS2"."A2_ASSAY_INSERT" 
 

before insert on A2_Assay
for each row
begin
if(:new.AssayID is null) then
select A2_Assay_seq.nextval into :new.AssayID from dual;
end if;
end;
/
ALTER TRIGGER "ATLAS2"."A2_ASSAY_INSERT" ENABLE;
 
