
  CREATE TABLE "ATLAS2"."A2_DESIGNELEMENT" 
   (	"DESIGNELEMENTID" NUMBER(22,0) NOT NULL ENABLE, 
	"ARRAYDESIGNID" NUMBER(22,0), 
	"GENEID" NUMBER(22,0) NOT NULL ENABLE, 
	"ACCESSION" VARCHAR2(255 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"TYPE" VARCHAR2(255 BYTE), 
	"ISCONTROL" NUMBER(22,0), 
	 CONSTRAINT "SYS_C008063" PRIMARY KEY ("DESIGNELEMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ATLAS2_INDX"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ATLAS2_DATA" ;
 

  CREATE OR REPLACE TRIGGER "ATLAS2"."A2_DesignElement_Insert" 
 

before insert on A2_DesignElement
for each row
begin
if(:new.DesignElementID is null) then
select A2_DesignElement_seq.nextval into :new.DesignElementID from dual;
end if;
end;
/
ALTER TRIGGER "ATLAS2"."A2_DesignElement_Insert" ENABLE;
 
