
  CREATE TABLE "ATLAS2"."A2_EXPRESSIONVALUE" 
   (	"EXPRESSIONVALUEID" NUMBER(22,0) NOT NULL ENABLE, 
	"DESIGNELEMENTID" NUMBER(22,0) NOT NULL ENABLE, 
	"EXPERIMENTID" NUMBER(22,0) NOT NULL ENABLE, 
	"ASSAYID" NUMBER(22,0) NOT NULL ENABLE, 
	"VALUE" FLOAT(126), 
	 CONSTRAINT "SYS_C008076" PRIMARY KEY ("EXPRESSIONVALUEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ATLAS2_INDX"  ENABLE, 
	 CONSTRAINT "FKA2_EXPRESS543264" FOREIGN KEY ("DESIGNELEMENTID")
	  REFERENCES "ATLAS2"."A2_DESIGNELEMENT" ("DESIGNELEMENTID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ATLAS2_DATA" ;
 

  CREATE OR REPLACE TRIGGER "ATLAS2"."A2_EXPRESSIONVALUE_INSERT" 
 

before insert on A2_ExpressionValue
for each row
begin
if(:new.ExpressionValueID is null) then
select A2_ExpressionValue_seq.nextval into :new.ExpressionValueID from dual;
end if
end;
/
ALTER TRIGGER "ATLAS2"."A2_EXPRESSIONVALUE_INSERT" ENABLE;
 
