
  CREATE TABLE "ATLAS2"."A2_GENEPROPERTY" 
   (	"GENEPROPERTYID" NUMBER(22,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 BYTE), 
	"AE2TABLENAME" VARCHAR2(255 BYTE), 
	 CONSTRAINT "SYS_C008045" PRIMARY KEY ("GENEPROPERTYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ATLAS2_INDX"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ATLAS2_DATA" ;
 

  CREATE OR REPLACE TRIGGER "ATLAS2"."A2_GENEProperty_INSERT" 
 

before insert on A2_GENEProperty
for each row
begin
if(:new.GENEPropertyID is null) then
select A2_GENEProperty_seq.nextval into :new.GENEPropertyID from dual;
end if;
end;
/
ALTER TRIGGER "ATLAS2"."A2_GENEProperty_INSERT" ENABLE;
 
