
  CREATE TABLE "ATLAS2"."A2_GENE" 
   (	"GENEID" NUMBER(*,0), 
	"SPECID" NUMBER(22,0) NOT NULL ENABLE, 
	"IDENTIFIER" VARCHAR2(255 BYTE), 
	"NAME" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ATLAS2_DATA" ;
 

  CREATE OR REPLACE TRIGGER "ATLAS2"."A2_GENE_INSERT" 
 

before insert on A2_GENE
for each row
begin
if(:new.GENEID is null) then
select A2_GENE_seq.nextval into :new.GENEID from dual;
end if;
end;
/
ALTER TRIGGER "ATLAS2"."A2_GENE_INSERT" ENABLE;
 
