
  CREATE TABLE "ATLAS2"."A2_PROPERTYVALUE" 
   (	"PROPERTYVALUEID" NUMBER(22,0) NOT NULL ENABLE, 
	"PROPERTYID" NUMBER(22,0), 
	"NAME" VARCHAR2(255 BYTE), 
	 CONSTRAINT "SYS_C008066" PRIMARY KEY ("PROPERTYVALUEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ATLAS2_INDX"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ATLAS2_DATA" ;
 

  CREATE OR REPLACE TRIGGER "ATLAS2"."A2_PROPERTYVALUE_INSERT" 
 

before insert on A2_PropertyValue
for each row
begin
if ( :new.PropertyValueID is null) then 
  select A2_PropertyValue_seq.nextval into :new.PropertyValueID from dual;
end if;
end;
/
ALTER TRIGGER "ATLAS2"."A2_PROPERTYVALUE_INSERT" ENABLE;
 
