
  CREATE TABLE "ATLAS2"."A2_SAMPLEPROPERTYVALUE" 
   (	"SAMPLEPROPERTYVALUEID" NUMBER(22,0) NOT NULL ENABLE, 
	"SAMPLEID" NUMBER(22,0) NOT NULL ENABLE, 
	"PROPERTYVALUEID" NUMBER(22,0), 
	"ISFACTORVALUE" NUMBER(22,0), 
	 CONSTRAINT "SYS_C008061" PRIMARY KEY ("SAMPLEPROPERTYVALUEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ATLAS2_INDX"  ENABLE, 
	 CONSTRAINT "FKA2_SAMPLEP915472" FOREIGN KEY ("SAMPLEID")
	  REFERENCES "ATLAS2"."A2_SAMPLE" ("SAMPLEID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ATLAS2_DATA" ;
 

  CREATE OR REPLACE TRIGGER "ATLAS2"."A2_SAMPLEPROPERTYVALUE_INSERT" 
 

before insert on A2_SamplePropertyValue
for each row
begin
if(:new.SamplePropertyValueID is null) then
select A2_SamplePropertyValue_seq.nextval into :new.SamplePropertyValueID from dual;
end if;
end;
/
ALTER TRIGGER "ATLAS2"."A2_SAMPLEPROPERTYVALUE_INSERT" ENABLE;
 
