SET HEAD OFF
set newp none
set recsep off
set echo off
set serveroutput off
set tab off
set line 500
set wrap off
SET FEEDBACK OFF 
SET VERIFY OFF 

select ROWNUM     || chr(9) || 
       PropertyID || chr(9) || 
       Value 
from (
select distinct PropertyID, TRIM(replace(Value,'  ',' ')) Value from (
select distinct 1 as PropertyID, Value from AE1__ASSAY_RNAI__DM UNION ALL                                                                                                                                                                                                                                                                                    
select distinct 2 as PropertyID, Value from AE1__ASSAY_AGE__DM UNION ALL                                                                                                                                                                                                                                                                                     
select distinct 3 as PropertyID, Value from AE1__ASSAY_CELLLINE__DM UNION ALL                                                                                                                                                                                                                                                                                
select distinct 4 as PropertyID, Value from AE1__ASSAY_CELLTYPE__DM UNION ALL                                                                                                                                                                                                                                                                                
select distinct 5 as PropertyID, Value from AE1__ASSAY_CLINHISTORY__DM UNION ALL                                                                                                                                                                                                                                                                             
select distinct 6 as PropertyID, Value from AE1__ASSAY_CLININFO__DM UNION ALL                                                                                                                                                                                                                                                                                
select distinct 7 as PropertyID, Value from AE1__ASSAY_CLINTREATMENT__DM UNION ALL                                                                                                                                                                                                                                                                           
select distinct 8 as PropertyID, Value from AE1__ASSAY_COMPOUND__DM UNION ALL                                                                                                                                                                                                                                                                                
select distinct 9 as PropertyID, Value from AE1__ASSAY_DEVSTAGE__DM UNION ALL                                                                                                                                                                                                                                                                                
select distinct 11 as PropertyID, Value from AE1__ASSAY_DISEASESTAGING__DM UNION ALL                                                                                                                                                                                                                                                                         
select distinct 12 as PropertyID, Value from AE1__ASSAY_DISEASESTATE__DM UNION ALL                                                                                                                                                                                                                                                                           
select distinct 13 as PropertyID, Value from AE1__ASSAY_DOSE__DM UNION ALL                                                                                                                                                                                                                                                                                   
select distinct 14 as PropertyID, Value from AE1__ASSAY_ECOTYPE__DM UNION ALL                                                                                                                                                                                                                                                                                
select distinct 15 as PropertyID, Value from AE1__ASSAY_GENMODIF__DM UNION ALL                                                                                                                                                                                                                                                                               
select distinct 16 as PropertyID, Value from AE1__ASSAY_GENOTYPE__DM UNION ALL                                                                                                                                                                                                                                                                               
select distinct 17 as PropertyID, Value from AE1__ASSAY_GROWTHCONDITION__DM UNION ALL                                                                                                                                                                                                                                                                        
select distinct 18 as PropertyID, Value from AE1__ASSAY_HISTOLOGY__DM UNION ALL                                                                                                                                                                                                                                                                              
select distinct 19 as PropertyID, Value from AE1__ASSAY_INDGENETICCHAR__DM UNION ALL                                                                                                                                                                                                                                                                         
select distinct 20 as PropertyID, Value from AE1__ASSAY_INDIVIDUAL__DM UNION ALL                                                                                                                                                                                                                                                                             
select distinct 21 as PropertyID, Value from AE1__ASSAY_INFECT__DM UNION ALL                                                                                                                                                                                                                                                                                 
select distinct 22 as PropertyID, Value from AE1__ASSAY_INJURY__DM UNION ALL                                                                                                                                                                                                                                                                                 
select distinct 23 as PropertyID, Value from AE1__ASSAY_LIGHT__DM UNION ALL                                                                                                                                                                                                                                                                                  
select distinct 24 as PropertyID, Value from AE1__ASSAY_MATERIALTYPE__DM UNION ALL                                                                                                                                                                                                                                                                           
select distinct 25 as PropertyID, Value from AE1__ASSAY_MEDIA__DM UNION ALL                                                                                                                                                                                                                                                                                  
select distinct 26 as PropertyID, Value from AE1__ASSAY_OBSERVATION__DM UNION ALL                                                                                                                                                                                                                                                                            
select distinct 27 as PropertyID, Value from AE1__ASSAY_ORGANISM__DM UNION ALL                                                                                                                                                                                                                                                                               
select distinct 28 as PropertyID, Value from AE1__ASSAY_ORGANISMPART__DM UNION ALL                                                                                                                                                                                                                                                                           
select distinct 29 as PropertyID, Value from AE1__ASSAY_PHENOTYPE__DM UNION ALL                                                                                                                                                                                                                                                                              
select distinct 30 as PropertyID, Value from AE1__ASSAY_PROTOCOLTYPE__DM UNION ALL                                                                                                                                                                                                                                                                           
select distinct 31 as PropertyID, Value from AE1__ASSAY_REPLICATE__DM UNION ALL                                                                                                                                                                                                                                                                              
select distinct 32 as PropertyID, Value from AE1__ASSAY_SEX__DM UNION ALL                                                                                                                                                                                                                                                                                    
select distinct 33 as PropertyID, Value from AE1__ASSAY_STRAINORLINE__DM UNION ALL                                                                                                                                                                                                                                                                           
select distinct 34 as PropertyID, Value from AE1__ASSAY_TARGETCELLTYPE__DM UNION ALL                                                                                                                                                                                                                                                                         
select distinct 35 as PropertyID, Value from AE1__ASSAY_TEMPERATURE__DM UNION ALL                                                                                                                                                                                                                                                                            
select distinct 36 as PropertyID, Value from AE1__ASSAY_TESTRESULT__DM UNION ALL                                                                                                                                                                                                                                                                             
select distinct 37 as PropertyID, Value from AE1__ASSAY_TIME__DM UNION ALL                                                                                                                                                                                                                                                                                   
select distinct 38 as PropertyID, Value from AE1__ASSAY_TUMORGRADING__DM UNION ALL                                                                                                                                                                                                                                                                           
select distinct 39 as PropertyID, Value from AE1__ASSAY_VEHICLE__DM UNION ALL                                                                                                                                                                                                                                                                                
select distinct 104 as PropertyID, Value from AE1__ASSAY_BIOMETRIC__DM UNION ALL                                                                                                                                                                                                                                                                             
select distinct 105 as PropertyID, Value from AE1__ASSAY_CULTIVAR__DM UNION ALL                                                                                                                                                                                                                                                                              
select distinct 106 as PropertyID, Value from AE1__ASSAY_DISEASELOC__DM UNION ALL                                                                                                                                                                                                                                                                            
select distinct 107 as PropertyID, Value from AE1__ASSAY_ENVHISTORY__DM UNION ALL                                                                                                                                                                                                                                                                            
select distinct 108 as PropertyID, Value from AE1__ASSAY_FAMILYHISTORY__DM UNION ALL                                                                                                                                                                                                                                                                         
select distinct 109 as PropertyID, Value from AE1__ASSAY_GENERATION__DM UNION ALL                                                                                                                                                                                                                                                                            
select distinct 110 as PropertyID, Value from AE1__ASSAY_INITIALTIME__DM UNION ALL                                                                                                                                                                                                                                                                           
select distinct 111 as PropertyID, Value from AE1__ASSAY_ORGANISMSTATUS__DM UNION ALL                                                                                                                                                                                                                                                                        
select distinct 112 as PropertyID, Value from AE1__ASSAY_PERFORMER__DM UNION ALL                                                                                                                                                                                                                                                                             
select distinct 113 as PropertyID, Value from AE1__ASSAY_POPULATION__DM UNION ALL                                                                                                                                                                                                                                                                            
select distinct 114 as PropertyID, Value from AE1__ASSAY_QCDESCRTYPE__DM UNION ALL                                                                                                                                                                                                                                                                           
select distinct 115 as PropertyID, Value from AE1__ASSAY_SOURCEPROVIDER__DM UNION ALL                                                                                                                                                                                                                                                                        
select distinct 116 as PropertyID, Value from AE1__ASSAY_TESTTYPE__DM UNION ALL                                                                                                                                                                                                                                                                              
select distinct 2 as PropertyID, Value from AE1__SAMPLE_AGE__DM UNION ALL                                                                                                                                                                                                                                                                                    
select distinct 3 as PropertyID, Value from AE1__SAMPLE_CELLLINE__DM UNION ALL                                                                                                                                                                                                                                                                               
select distinct 4 as PropertyID, Value from AE1__SAMPLE_CELLTYPE__DM UNION ALL                                                                                                                                                                                                                                                                               
select distinct 5 as PropertyID, Value from AE1__SAMPLE_CLINHISTORY__DM UNION ALL                                                                                                                                                                                                                                                                            
select distinct 6 as PropertyID, Value from AE1__SAMPLE_CLININFO__DM UNION ALL                                                                                                                                                                                                                                                                               
select distinct 7 as PropertyID, Value from AE1__SAMPLE_CLINTREATMENT__DM UNION ALL                                                                                                                                                                                                                                                                          
select distinct 9 as PropertyID, Value from AE1__SAMPLE_DEVSTAGE__DM UNION ALL                                                                                                                                                                                                                                                                               
select distinct 11 as PropertyID, Value from AE1__SAMPLE_DISEASESTAGING__DM UNION ALL                                                                                                                                                                                                                                                                        
select distinct 12 as PropertyID, Value from AE1__SAMPLE_DISEASESTATE__DM UNION ALL                                                                                                                                                                                                                                                                          
select distinct 14 as PropertyID, Value from AE1__SAMPLE_ECOTYPE__DM UNION ALL                                                                                                                                                                                                                                                                               
select distinct 15 as PropertyID, Value from AE1__SAMPLE_GENMODIF__DM UNION ALL                                                                                                                                                                                                                                                                              
select distinct 16 as PropertyID, Value from AE1__SAMPLE_GENOTYPE__DM UNION ALL                                                                                                                                                                                                                                                                              
select distinct 18 as PropertyID, Value from AE1__SAMPLE_HISTOLOGY__DM UNION ALL                                                                                                                                                                                                                                                                             
select distinct 19 as PropertyID, Value from AE1__SAMPLE_INDGENETICCHAR__DM UNION ALL                                                                                                                                                                                                                                                                        
select distinct 20 as PropertyID, Value from AE1__SAMPLE_INDIVIDUAL__DM UNION ALL                                                                                                                                                                                                                                                                            
select distinct 26 as PropertyID, Value from AE1__SAMPLE_OBSERVATION__DM UNION ALL                                                                                                                                                                                                                                                                           
select distinct 28 as PropertyID, Value from AE1__SAMPLE_ORGANISMPART__DM UNION ALL                                                                                                                                                                                                                                                                          
select distinct 29 as PropertyID, Value from AE1__SAMPLE_PHENOTYPE__DM UNION ALL                                                                                                                                                                                                                                                                             
select distinct 32 as PropertyID, Value from AE1__SAMPLE_SEX__DM UNION ALL                                                                                                                                                                                                                                                                                   
select distinct 33 as PropertyID, Value from AE1__SAMPLE_STRAINORLINE__DM UNION ALL                                                                                                                                                                                                                                                                          
select distinct 34 as PropertyID, Value from AE1__SAMPLE_TARGETCELLTYPE__DM UNION ALL                                                                                                                                                                                                                                                                        
select distinct 36 as PropertyID, Value from AE1__SAMPLE_TESTRESULT__DM UNION ALL                                                                                                                                                                                                                                                                            
select distinct 38 as PropertyID, Value from AE1__SAMPLE_TUMORGRADING__DM UNION ALL                                                                                                                                                                                                                                                                          
select distinct 104 as PropertyID, Value from AE1__SAMPLE_BIOMETRIC__DM UNION ALL                                                                                                                                                                                                                                                                            
select distinct 105 as PropertyID, Value from AE1__SAMPLE_CULTIVAR__DM UNION ALL                                                                                                                                                                                                                                                                             
select distinct 106 as PropertyID, Value from AE1__SAMPLE_DISEASELOC__DM UNION ALL                                                                                                                                                                                                                                                                           
select distinct 107 as PropertyID, Value from AE1__SAMPLE_ENVHISTORY__DM UNION ALL                                                                                                                                                                                                                                                                           
select distinct 108 as PropertyID, Value from AE1__SAMPLE_FAMILYHISTORY__DM UNION ALL                                                                                                                                                                                                                                                                        
select distinct 110 as PropertyID, Value from AE1__SAMPLE_INITIALTIME__DM UNION ALL                                                                                                                                                                                                                                                                          
select distinct 111 as PropertyID, Value from AE1__SAMPLE_ORGANISMSTATUS__DM UNION ALL                                                                                                                                                                                                                                                                       
select distinct 115 as PropertyID, Value from AE1__SAMPLE_SOURCEPROVIDER__DM UNION ALL                                                                                                                                                                                                                                                                       
select distinct 116 as PropertyID, Value from AE1__SAMPLE_TESTTYPE__DM)
where value is not null);

quit;
