SET HEAD OFF
set newp none
set recsep off
set echo off
set serveroutput off
set tab off
set line 500
set wrap off
SET FEEDBACK OFF
SET VERIFY OFF

select ROWNUM        || chr(9) || 
       Sample_ID_KEY || chr(9) || 
       PropertyID    || chr(9) || 
       value
from (
select distinct sample_id_key, propertyid, TRIM(replace(Value,'  ', ' ')) VALUE
from (
select distinct Sample_ID_KEY, 2 as PropertyID, Value from AE1__SAMPLE_AGE__DM UNION ALL                                                                                                                                                                                                                                                                                    
select distinct Sample_ID_KEY, 3 as PropertyID,  Value from AE1__SAMPLE_CELLLINE__DM UNION ALL                                                                                                                                                                                                                                                                               
select distinct Sample_ID_KEY, 4 as PropertyID,  Value from AE1__SAMPLE_CELLTYPE__DM UNION ALL                                                                                                                                                                                                                                                                               
select distinct Sample_ID_KEY, 5 as PropertyID,  Value from AE1__SAMPLE_CLINHISTORY__DM UNION ALL                                                                                                                                                                                                                                                                            
select distinct Sample_ID_KEY, 6 as PropertyID,  Value from AE1__SAMPLE_CLININFO__DM UNION ALL                                                                                                                                                                                                                                                                               
select distinct Sample_ID_KEY, 7 as PropertyID,  Value from AE1__SAMPLE_CLINTREATMENT__DM UNION ALL                                                                                                                                                                                                                                                                          
select distinct Sample_ID_KEY, 9 as PropertyID,  Value from AE1__SAMPLE_DEVSTAGE__DM UNION ALL                                                                                                                                                                                                                                                                               
select distinct Sample_ID_KEY, 11 as PropertyID,  Value from AE1__SAMPLE_DISEASESTAGING__DM UNION ALL                                                                                                                                                                                                                                                                        
select distinct Sample_ID_KEY, 12 as PropertyID,  Value from AE1__SAMPLE_DISEASESTATE__DM UNION ALL                                                                                                                                                                                                                                                                          
select distinct Sample_ID_KEY, 14 as PropertyID,  Value from AE1__SAMPLE_ECOTYPE__DM UNION ALL                                                                                                                                                                                                                                                                               
select distinct Sample_ID_KEY, 15 as PropertyID,  Value from AE1__SAMPLE_GENMODIF__DM UNION ALL                                                                                                                                                                                                                                                                              
select distinct Sample_ID_KEY, 16 as PropertyID,  Value from AE1__SAMPLE_GENOTYPE__DM UNION ALL                                                                                                                                                                                                                                                                              
select distinct Sample_ID_KEY, 18 as PropertyID,  Value from AE1__SAMPLE_HISTOLOGY__DM UNION ALL                                                                                                                                                                                                                                                                             
select distinct Sample_ID_KEY, 19 as PropertyID,  Value from AE1__SAMPLE_INDGENETICCHAR__DM UNION ALL                                                                                                                                                                                                                                                                        
select distinct Sample_ID_KEY, 20 as PropertyID,  Value from AE1__SAMPLE_INDIVIDUAL__DM UNION ALL                                                                                                                                                                                                                                                                            
select distinct Sample_ID_KEY, 26 as PropertyID,  Value from AE1__SAMPLE_OBSERVATION__DM UNION ALL                                                                                                                                                                                                                                                                           
select distinct Sample_ID_KEY, 28 as PropertyID,  Value from AE1__SAMPLE_ORGANISMPART__DM UNION ALL                                                                                                                                                                                                                                                                          
select distinct Sample_ID_KEY, 29 as PropertyID,  Value from AE1__SAMPLE_PHENOTYPE__DM UNION ALL                                                                                                                                                                                                                                                                             
select distinct Sample_ID_KEY, 32 as PropertyID,  Value from AE1__SAMPLE_SEX__DM UNION ALL                                                                                                                                                                                                                                                                                   
select distinct Sample_ID_KEY, 33 as PropertyID,  Value from AE1__SAMPLE_STRAINORLINE__DM UNION ALL                                                                                                                                                                                                                                                                          
select distinct Sample_ID_KEY, 34 as PropertyID,  Value from AE1__SAMPLE_TARGETCELLTYPE__DM UNION ALL                                                                                                                                                                                                                                                                        
select distinct Sample_ID_KEY, 36 as PropertyID,  Value from AE1__SAMPLE_TESTRESULT__DM UNION ALL                                                                                                                                                                                                                                                                            
select distinct Sample_ID_KEY, 38 as PropertyID,  Value from AE1__SAMPLE_TUMORGRADING__DM UNION ALL                                                                                                                                                                                                                                                                          
select distinct Sample_ID_KEY, 104 as PropertyID,  Value from AE1__SAMPLE_BIOMETRIC__DM UNION ALL                                                                                                                                                                                                                                                                            
select distinct Sample_ID_KEY, 105 as PropertyID,  Value from AE1__SAMPLE_CULTIVAR__DM UNION ALL                                                                                                                                                                                                                                                                             
select distinct Sample_ID_KEY, 106 as PropertyID,  Value from AE1__SAMPLE_DISEASELOC__DM UNION ALL                                                                                                                                                                                                                                                                           
select distinct Sample_ID_KEY, 107 as PropertyID,  Value from AE1__SAMPLE_ENVHISTORY__DM UNION ALL                                                                                                                                                                                                                                                                           
select distinct Sample_ID_KEY, 108 as PropertyID,  Value from AE1__SAMPLE_FAMILYHISTORY__DM UNION ALL                                                                                                                                                                                                                                                                        
select distinct Sample_ID_KEY, 110 as PropertyID,  Value from AE1__SAMPLE_INITIALTIME__DM UNION ALL                                                                                                                                                                                                                                                                          
select distinct Sample_ID_KEY, 111 as PropertyID,  Value from AE1__SAMPLE_ORGANISMSTATUS__DM UNION ALL                                                                                                                                                                                                                                                                       
select distinct Sample_ID_KEY, 115 as PropertyID,  Value from AE1__SAMPLE_SOURCEPROVIDER__DM UNION ALL                                                                                                                                                                                                                                                                       
select distinct Sample_ID_KEY, 116 as PropertyID,  Value from AE1__SAMPLE_TESTTYPE__DM where value is not null) t    
where value is not null and
    exists(select 1 from AE1__SAMPLE__MAIN 
    where AE1__SAMPLE__MAIN.SAMPLE_ID_KEY = t.SAMPLE_ID_KEY
    and   AE1__SAMPLE__MAIN.arraydesign_id is not null));

quit;


