  ALTER TABLE "A2_EXPRESSIONANALYTICS" 
  ADD CONSTRAINT "PK_EXPRESSIONANALYTICS" 
  PRIMARY KEY ("EXPRESSIONID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255  
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) 
  TABLESPACE ATLAS2TEST_INDX ENABLE;



select count(1) from a2_expressionanalytics

commit
153341531

call tmp_AnalyticsEnd();

create or replace procedure tmp_AnalyticsEnd as 
begin
  CREATE INDEX "A2_IDX_EXPRESSION_FV" ON "A2_EXPRESSIONANALYTICS" ("PROPERTYVALUEID") TABLESPACE ATLAS2TEST_INDX;
  CREATE INDEX "IDX_ANALYTICS_DESIGNELEMENT" ON "A2_EXPRESSIONANALYTICS" ("DESIGNELEMENTID") TABLESPACE ATLAS2TEST_INDX;
  CREATE INDEX "IDX_EA_EXPERIMENT" ON "A2_EXPRESSIONANALYTICS" ("EXPERIMENTID") TABLESPACE ATLAS2TEST_INDX;
    
  ALTER TABLE "A2_EXPRESSIONANALYTICS" ADD CONSTRAINT "FK_ANALYTICS_EXPERIMENT" FOREIGN KEY ("EXPERIMENTID") REFERENCES "A2_EXPERIMENT" ("EXPERIMENTID") ENABLE;
  ALTER TABLE "A2_EXPRESSIONANALYTICS" ADD CONSTRAINT "FK_ANALYTICS_PROPERTYVALUE" FOREIGN KEY ("PROPERTYVALUEID") REFERENCES "A2_PROPERTYVALUE" ("PROPERTYVALUEID") ENABLE;

  ALTER TRIGGER "A2_ExpressionAnalytics_Insert" ENABLE;

end