OPTIONS(ROWS=1000000,DIRECT=TRUE)
load data
infile 'Data/ExpressionAnalytics.dat'
truncate into table a2_ExpressionAnalytics
fields terminated by "\t" 
TRAILING NULLCOLS
(EXPRESSIONID,EXPERIMENTID,DESIGNELEMENTID,PROPERTYID FILLER,PROPERTYVALUEID,TSTAT,PVALADJ,FPVAL,FPVALADJ)
