 /*
 * Copyright 2008-2010 Microarray Informatics Team, EMBL-European Bioinformatics Institute
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 * For further details of the Gene Expression Atlas project, including source code,
 * downloads and documentation, please see:
 *
 * http://gxa.github.com/gxa/
 */

 /*******************************************************************************/
/*  Tables, Sequences, Indexes and Triggers in Atlas2 schema
/*
/*
/*******************************************************************************/

--------------------------------------------------------
--  ORGANISM
--------------------------------------------------------
  CREATE SEQUENCE  "A2_ORGANISM_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;
    

  CREATE TABLE "A2_ORGANISM" (
    "ORGANISMID" NUMBER(22,0) CONSTRAINT NN_ORGANISM_ORGANISMID NOT NULL
  , "NAME" VARCHAR2(255) CONSTRAINT NN_ORGANISM_NAME NOT NULL);
  

  ALTER TABLE "A2_ORGANISM" 
  ADD CONSTRAINT "PK_ORGANISM" 
    PRIMARY KEY ("ORGANISMID") 
  /*PK_TABLESPACE*/
  ENABLE;


  ALTER TABLE "A2_ORGANISM" 
  ADD CONSTRAINT "UQ_ORGANISM_NAME" 
    UNIQUE("NAME") 
    ENABLE;


CREATE OR REPLACE TRIGGER "A2_ORGANISM_INSERT"  
before insert on A2_ORGANISM
for each row
begin
if(:new.ORGANISMID is null) then
select A2_ORGANISM_seq.nextval into :new.ORGANISMID from dual;
end if;
end;
/

ALTER TRIGGER "A2_ORGANISM_INSERT" ENABLE;


Insert into A2_Organism(OrganismID,Name)
select a2_organism_seq.nextval,'Unknown' from dual
where not exists(select 1 from a2_Organism where name = 'Unknown');


--------------------------------------------------------
-- GENE PROPERTY
-- ALTER TABLE A2_GENEPROPERTY ADD "IDENTIFIERPRIORITY" NUMBER(22,0)
--------------------------------------------------------
 CREATE SEQUENCE  "A2_GENEPROPERTY_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;


  CREATE TABLE "A2_GENEPROPERTY" (
    "GENEPROPERTYID" NUMBER(22,0)  CONSTRAINT NN_GENEPROPERTY_ID NOT NULL 
  , "NAME" VARCHAR2(255) CONSTRAINT NN_GENEPROPERTY_NAME NOT NULL
  , "AE2TABLENAME" VARCHAR2(255) 
  , "IDENTIFIERPRIORITY" NUMBER(22,0));


  ALTER TABLE "A2_GENEPROPERTY" 
  ADD CONSTRAINT "PK_GENEPROPERTY" 
    PRIMARY KEY ("GENEPROPERTYID") 
    /*PK_TABLESPACE*/
    ENABLE;


  ALTER TABLE "A2_GENEPROPERTY" 
  ADD CONSTRAINT "UQ_GENEPROPERTY_NAME" 
    UNIQUE("NAME") 
    ENABLE; 


CREATE OR REPLACE TRIGGER A2_GENEPROPERTY_INSERT  
before insert on A2_GENEProperty
for each row
begin
if(:new.GENEPropertyID is null) then
select A2_GENEProperty_seq.nextval into :new.GENEPropertyID from dual;
end if;
end;
/

ALTER TRIGGER A2_GENEProperty_INSERT ENABLE;      


Insert into A2_GENEPROPERTY (GenePropertyID,Name,IDENTIFIERPRIORITY)
Select 1,'ensembl',1 from dual
where not exists(select 1 from a2_geneproperty where Name = 'ensembl');

Insert into A2_GENEPROPERTY (GenePropertyID,Name,IDENTIFIERPRIORITY)
Select 2,'ensgene',2 from dual
where not exists(select 1 from a2_geneproperty where Name = 'ensgene');

Insert into A2_GENEPROPERTY (GenePropertyID,Name,IDENTIFIERPRIORITY)
Select 3,'uniprot',3 from dual
where not exists(select 1 from a2_geneproperty where Name = 'uniprot');

Insert into a2_GeneProperty (GenePropertyID, Name, AE2TABLENAME, IDENTIFIERPRIORITY)
select 33, 'mirna', null, 4 from dual
where not exists(select 1 from a2_geneproperty where Name = 'mirna');

commit;

--------------------------------------------------------
-- GENE PROPERTYVALUE
--------------------------------------------------------
 CREATE SEQUENCE  "A2_GENEPROPERTYVALUE_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;


  CREATE TABLE "A2_GENEPROPERTYVALUE" (
    "GENEPROPERTYVALUEID" NUMBER(22,0) CONSTRAINT NN_GPV_ID NOT NULL
  , "GENEPROPERTYID" NUMBER(22,0) CONSTRAINT NN_GPV_GENEPROPERTYID NOT NULL
  , "VALUE" VARCHAR2(255) CONSTRAINT NN_GPV_VALUE NOT NULL); 


  ALTER TABLE "A2_GENEPROPERTYVALUE" 
  ADD CONSTRAINT "PK_GENEPROPERTYVALUE" 
    PRIMARY KEY ("GENEPROPERTYVALUEID") 
    /*PK_TABLESPACE*/
    ENABLE; 


  CREATE INDEX "IDX_GENEPROPERTYVALUE_PROPERTY" 
  ON "A2_GENEPROPERTYVALUE" ("GENEPROPERTYID") 
  /*INDEX_TABLESPACE*/;  


  ALTER TABLE "A2_GENEPROPERTYVALUE" 
  ADD CONSTRAINT "FK_GENEPROPERTYVALUE_PROPERTY" 
    FOREIGN KEY ("GENEPROPERTYID") 
    REFERENCES "A2_GENEPROPERTY" ("GENEPROPERTYID") 
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_GENEPROPERTYVALUE" 
  ADD CONSTRAINT "UQ_GENEPROPERTYVALUE_VALUE" 
    UNIQUE("GENEPROPERTYID","VALUE") 
    ENABLE; 


CREATE OR REPLACE TRIGGER A2_GENEPROPERTYVALUE_INSERT  
before insert on A2_GENEPropertyValue
for each row
begin
if(:new.GENEPropertyValueID is null) then
select A2_GENEPropertyValue_seq.nextval into :new.GENEPropertyValueID from dual;
end if;
end;
/

ALTER TRIGGER A2_GENEPropertyValue_INSERT ENABLE;

--------------------------------------------------------
-- GENE 
--------------------------------------------------------
 CREATE SEQUENCE  "A2_GENE_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;


 CREATE TABLE "A2_GENE" (
    "GENEID" NUMBER(22,0) CONSTRAINT NN_GENE_ID NOT NULL
  , "ORGANISMID" NUMBER(22,0) CONSTRAINT NN_GENE_ORGANISMID NOT NULL
  , "IDENTIFIER" VARCHAR2(255) CONSTRAINT NN_GENE_IDENTIFIER NOT NULL
  , "NAME" VARCHAR2(255) /*CONSTRAINT NN_GENE_NAME NOT NULL*/);    


  ALTER TABLE "A2_GENE" 
  ADD CONSTRAINT "PK_GENE" 
    PRIMARY KEY ("GENEID") 
    /*PK_TABLESPACE*/
    ENABLE;


  CREATE INDEX "IDX_GENE_ORGANISM" 
  ON "A2_GENE" ("ORGANISMID") 
  /*INDEX_TABLESPACE*/;


  ALTER TABLE "A2_GENE" 
  ADD CONSTRAINT "FK_GENE_ORGANISM" 
    FOREIGN KEY ("ORGANISMID") 
    REFERENCES "A2_ORGANISM" ("ORGANISMID") 
    ON DELETE CASCADE
    ENABLE;


 ALTER TABLE "A2_GENE" 
  ADD CONSTRAINT "UQ_GENE_IDENTIFIER" 
    UNIQUE("IDENTIFIER") 
    ENABLE;


CREATE OR REPLACE TRIGGER A2_GENE_INSERT  
before insert on A2_GENE
for each row
begin
if(:new.GENEID is null) then
select A2_GENE_seq.nextval into :new.GENEID from dual;
end if;

if(:new.OrganismID is null) then
select OrganismID into :new.OrganismID from a2_Organism where Name = 'unknown';
end if;

end;
/

ALTER TRIGGER A2_GENE_INSERT ENABLE;


--------------------------------------------------------
-- GENE GENEPROPERTYVALUE
--------------------------------------------------------
  CREATE SEQUENCE  "A2_GENEGPV_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;


  CREATE TABLE "A2_GENEGPV" (
    "GENEGPVID" NUMBER(22,0) CONSTRAINT NN_GENEGPV_ID NOT NULL
  , "GENEID" NUMBER(22,0)  CONSTRAINT NN_GENEGPV_GENEID NOT NULL
  , "GENEPROPERTYVALUEID" NUMBER(22,0)  CONSTRAINT NN_GENEGPV_GPVID NOT NULL);


  ALTER TABLE "A2_GENEGPV" 
  ADD CONSTRAINT "PK_GENEGPV" 
    PRIMARY KEY ("GENEGPVID") 
    /*PK_TABLESPACE*/
    ENABLE;


  CREATE INDEX "IDX_GENEGPV_PROPERTY" 
  ON "A2_GENEGPV" ("GENEPROPERTYVALUEID") 
  /*INDEX_TABLESPACE*/;


  CREATE INDEX "IDX_GENEGPV_GENE" 
  ON "A2_GENEGPV" ("GENEID") 
  /*INDEX_TABLESPACE*/;


  ALTER TABLE "A2_GENEGPV" 
  ADD CONSTRAINT "FK_GENEGPV_GENE" 
    FOREIGN KEY ("GENEID") 
    REFERENCES "A2_GENE" ("GENEID") 
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_GENEGPV" 
  ADD CONSTRAINT "FK_GENEGPV_GPV" 
    FOREIGN KEY ("GENEPROPERTYVALUEID") 
    REFERENCES "A2_GENEPROPERTYVALUE" ("GENEPROPERTYVALUEID") 
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_GENEGPV" 
  ADD CONSTRAINT "UQ_GENEGPV" 
    UNIQUE("GENEID","GENEPROPERTYVALUEID") 
    ENABLE;    


CREATE OR REPLACE TRIGGER A2_GENEGPV_INSERT  
before insert on A2_GENEGPV
for each row
begin
if(:new.GENEGPVID is null) then
select A2_GENEGPV_seq.nextval into :new.GENEGPVID from dual;
end if;
end;
/

ALTER TRIGGER A2_GENEGPV_INSERT ENABLE;

--------------------------------------------------------
--  MAPPING SOURCE
--------------------------------------------------------
  CREATE SEQUENCE  "A2_SOFTWARE_SEQ"
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;


  CREATE TABLE "A2_SOFTWARE" (
    "SOFTWAREID" NUMBER(22,0) CONSTRAINT NN_SOFTWARE_ID NOT NULL
  , "NAME" VARCHAR2(255) CONSTRAINT NN_SOFTWARE_NAME NOT NULL
  , "VERSION" VARCHAR2(255));


  ALTER TABLE "A2_SOFTWARE"
  ADD CONSTRAINT "PK_SOFTWARE"
    PRIMARY KEY ("SOFTWAREID")
  /*PK_TABLESPACE*/
  ENABLE;


  ALTER TABLE "A2_SOFTWARE"
  ADD CONSTRAINT "UQ_SOFTWARE_NAME_VERSION"
    UNIQUE("NAME", "VERSION")
    ENABLE;


CREATE OR REPLACE TRIGGER "A2_SOFTWARE_INSERT"
before insert on A2_SOFTWARE
for each row
begin
if(:new.SOFTWAREID is null) then
select A2_SOFTWARE_seq.nextval into :new.SOFTWAREID from dual;
end if;
end;
/

ALTER TRIGGER "A2_SOFTWARE_INSERT" ENABLE;

    
--------------------------------------------------------
-- ARRAY DESIGN
--------------------------------------------------------
 CREATE SEQUENCE  "A2_ARRAYDESIGN_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;


  CREATE TABLE "A2_ARRAYDESIGN" (
    "ARRAYDESIGNID" NUMBER(22,0) CONSTRAINT NN_ARRAYDESIGN_ID NOT NULL
  , "ACCESSION" VARCHAR2(255) CONSTRAINT NN_ARRAYDESIGN_ACCESSION NOT NULL
  , "TYPE" VARCHAR2(255) 
  , "NAME" VARCHAR2(255) CONSTRAINT NN_ARRAYDESIGN_NAME NOT NULL
  , "PROVIDER" VARCHAR2(255)
  , "LOADDATE" DATE,
  , "SYNONYMS" VARCHAR2(4000))
 ;


  ALTER TABLE "A2_ARRAYDESIGN" 
  ADD CONSTRAINT "PK_ARRAYDESIGN" 
    PRIMARY KEY ("ARRAYDESIGNID") 
    /*PK_TABLESPACE*/
    ENABLE;


  CREATE INDEX "IDX_ARRAYDESIGN_ACCESSION" 
  ON "A2_ARRAYDESIGN" ("ACCESSION") 
  /*INDEX_TABLESPACE*/;

  ALTER TABLE "A2_ARRAYDESIGN" 
  ADD CONSTRAINT "UQ_ARRAYDESIGN_NAME" 
    UNIQUE("NAME") 
    ENABLE;


  ALTER TABLE "A2_ARRAYDESIGN" 
  ADD CONSTRAINT "UQ_ARRAYDESIGN_ACCESSION" 
    UNIQUE("ACCESSION") 
    ENABLE;

CREATE OR REPLACE TRIGGER A2_ArrayDesign_Insert  
before insert on A2_ArrayDesign
for each row
begin
if( :new.ArrayDesignID is null) then
select A2_ArrayDesign_seq.nextval into :new.ArrayDesignID from dual;
end if;

if(( :new.LOADDATE is null)and(:old.LOADDATE is null)) then
select SYSDATE into :new.LOADDATE from dual;
end if;
end;
/

ALTER TRIGGER A2_ArrayDesign_Insert ENABLE;

--------------------------------------------------------
-- DESIGN ELEMENT
--------------------------------------------------------
 CREATE SEQUENCE  "A2_DESIGNELEMENT_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;


 CREATE TABLE "A2_DESIGNELEMENT" (
    "DESIGNELEMENTID" NUMBER(22,0) CONSTRAINT NN_DESIGNELEMENT_ID NOT NULL
  , "ARRAYDESIGNID" NUMBER(22,0) CONSTRAINT NN_DESIGNELEMENT_ARRAYDESIGNID NOT NULL
  , "GENEID" NUMBER(22,0) 
  , "ACCESSION" VARCHAR2(255) CONSTRAINT NN_DESIGNELEMENT_ACCESSION NOT NULL
  , "NAME" VARCHAR2(255)
  , "TYPE" VARCHAR2(255)
  , "ISCONTROL" NUMBER(22,0));


  ALTER TABLE "A2_DESIGNELEMENT" 
  ADD CONSTRAINT "PK_DESIGNELEMENT" 
    PRIMARY KEY ("DESIGNELEMENTID") 
    /*PK_TABLESPACE*/
    ENABLE;


  CREATE INDEX "IDX_DESIGNELEMENT_GENE" 
  ON "A2_DESIGNELEMENT" ("GENEID") 
  /*INDEX_TABLESPACE*/;


  CREATE INDEX "IDX_DESIGNELEMENT_ARRAYDESIGN" 
  ON "A2_DESIGNELEMENT" ("ARRAYDESIGNID") 
  /*INDEX_TABLESPACE*/;


  ALTER TABLE "A2_DESIGNELEMENT" 
  ADD CONSTRAINT "FK_DESIGNELEMENT_ARRAYDESIGN" 
    FOREIGN KEY ("ARRAYDESIGNID") 
    REFERENCES "A2_ARRAYDESIGN" ("ARRAYDESIGNID") 
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_DESIGNELEMENT" 
    ADD CONSTRAINT "FK_DESIGNELEMENT_GENE" 
    FOREIGN KEY ("GENEID") 
    REFERENCES "A2_GENE" ("GENEID") 
    ON DELETE CASCADE
    ENABLE;


  --ALTER TABLE "A2_DESIGNELEMENT" ADD CONSTRAINT "UQ_DESIGNELEMENT_NAME" UNIQUE("ARRAYDESIGNID","NAME") ENABLE;

  ALTER TABLE "A2_DESIGNELEMENT" 
  ADD CONSTRAINT "UQ_DESIGNELEMENT_ACCESSION" 
    UNIQUE("ARRAYDESIGNID","ACCESSION") 
    ENABLE;


CREATE OR REPLACE TRIGGER A2_DesignElement_Insert  
before insert on A2_DesignElement
for each row
begin
if(:new.DesignElementID is null) then
select A2_DesignElement_seq.nextval into :new.DesignElementID from dual;
end if;
end;
/

ALTER TRIGGER A2_DesignElement_Insert ENABLE;


--------------------------------------------------------
-- PROPERTY
--------------------------------------------------------
 CREATE SEQUENCE  "A2_PROPERTY_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;


 CREATE TABLE "A2_PROPERTY" (
    "PROPERTYID" NUMBER(22,0) CONSTRAINT NN_PROPERTY_ID NOT NULL,
    "NAME" VARCHAR2(255) CONSTRAINT NN_PROPERTY_NAME NOT NULL,
    "DISPLAYNAME" VARCHAR2(512));

  ALTER TABLE "A2_PROPERTY" 
  ADD CONSTRAINT "PK_PROPERTY" 
    PRIMARY KEY ("PROPERTYID") 
    /*PK_TABLESPACE*/
    ENABLE;


  CREATE INDEX "IDX_PROPERTY_NAME" 
  ON "A2_PROPERTY" ("NAME") 
  /*INDEX_TABLESPACE*/;


  ALTER TABLE "A2_PROPERTY" 
  ADD CONSTRAINT "UQ_PROPERTY_NAME" 
    UNIQUE("NAME") 
    ENABLE;


CREATE OR REPLACE TRIGGER A2_PROPERTY_INSERT  
before insert on A2_Property
for each row
begin
if(:new.PropertyID is null) then
  select A2_Property_seq.nextval into :new.PropertyID from dual;
end if;
end;
/

ALTER TRIGGER A2_PROPERTY_INSERT ENABLE;


--------------------------------------------------------
-- PROPERTY VALUE
--------------------------------------------------------
 CREATE SEQUENCE  "A2_PROPERTYVALUE_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;


 CREATE TABLE "A2_PROPERTYVALUE" (
    "PROPERTYVALUEID" NUMBER(22,0) CONSTRAINT NN_PROPERTYVALUE_ID NOT NULL
  , "PROPERTYID" NUMBER(22,0) CONSTRAINT NN_PROPERTYVALUE_PROPERTYID NOT NULL
  , "NAME" VARCHAR2(255) CONSTRAINT NN_PROPERTYVALUE_NAME NOT NULL
  , "DISPLAYNAME" VARCHAR2(512));


  ALTER TABLE "A2_PROPERTYVALUE" 
  ADD CONSTRAINT "PK_PROPERTYVALUE" 
    PRIMARY KEY ("PROPERTYVALUEID") 
  /*PK_TABLESPACE*/
  ENABLE;


  CREATE INDEX "IDX_PROPERTYVALUE_NAME" 
  ON "A2_PROPERTYVALUE" ("NAME") 
  /*INDEX_TABLESPACE*/;


  CREATE INDEX "IDX_PROPERTYVALUE_PROPERTY" 
  ON "A2_PROPERTYVALUE" ("PROPERTYID") 
  /*INDEX_TABLESPACE*/;

  ALTER TABLE "A2_PROPERTYVALUE" 
  ADD CONSTRAINT "FK_PROPERTYVALUE_PROPERTY" 
    FOREIGN KEY ("PROPERTYID") 
    REFERENCES "A2_PROPERTY" ("PROPERTYID") 
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_PROPERTYVALUE" 
  ADD CONSTRAINT "UQ_PROPERTYVALUE_NAME" 
    UNIQUE("PROPERTYID","NAME") 
    ENABLE;


CREATE OR REPLACE TRIGGER A2_PROPERTYVALUE_INSERT  
before insert on A2_PropertyValue
for each row
begin
if ( :new.PropertyValueID is null) then 
  select A2_PropertyValue_seq.nextval into :new.PropertyValueID from dual;
end if;
end;
/

ALTER TRIGGER A2_PROPERTYVALUE_INSERT ENABLE;


--------------------------------------------------------
-- EXPERIMENT
--------------------------------------------------------
 CREATE SEQUENCE  "A2_EXPERIMENT_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;


 CREATE TABLE "A2_EXPERIMENT" (
    "EXPERIMENTID" NUMBER(22,0) CONSTRAINT NN_EXPERIMENT_ID NOT NULL
  , "ACCESSION" VARCHAR2(255) CONSTRAINT NN_EXPERIMENT_ACCESSION NOT NULL
  , "DESCRIPTION" VARCHAR2(2000) 
  , "PERFORMER" VARCHAR2(2000)
  , "LAB" VARCHAR2(2000)
  , "PMID" VARCHAR2(255)
  , "ABSTRACT" VARCHAR2(2000)
  , "LOADDATE" DATE
  , "RELEASEDATE" DATE
  , "PRIVATE" NUMBER(1)
  );


  ALTER TABLE "A2_EXPERIMENT" 
  ADD CONSTRAINT "PK_EXPERIMENT" 
    PRIMARY KEY ("EXPERIMENTID") 
    /*PK_TABLESPACE*/
    ENABLE;


  CREATE INDEX "IDX_EXPERIMENT_ACCESSION" 
  ON "A2_EXPERIMENT" ("ACCESSION") 
  /*INDEX_TABLESPACE*/;


  ALTER TABLE "A2_EXPERIMENT" 
  ADD CONSTRAINT "UQ_EXPERIMENT_ACCESSION" 
    UNIQUE("ACCESSION") 
    ENABLE;


CREATE OR REPLACE TRIGGER A2_EXPERIMENT_INSERT  
before insert on A2_Experiment
for each row
begin
if(:new.ExperimentID is null) then
  select A2_Experiment_seq.nextval into :new.ExperimentID from dual;
end if;
end;
/

ALTER TRIGGER A2_EXPERIMENT_INSERT ENABLE;

--------------------------------------------------------
-- ASSET - file,figure,picture,etc. COMMIT
--------------------------------------------------------
 CREATE SEQUENCE  "A2_EXPERIMENTASSET_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;

 CREATE TABLE "A2_EXPERIMENTASSET" (
    "EXPERIMENTASSETID" NUMBER CONSTRAINT NN_EASSET_ID NOT NULL
  , "EXPERIMENTID" NUMBER CONSTRAINT NN_EASSET_EXPERIMENTID NOT NULL
  , "NAME" VARCHAR2(255) 
  , "FILENAME" VARCHAR2(255)
  , "DESCRIPTION" VARCHAR2(2000));    

 ALTER TABLE "A2_EXPERIMENTASSET" 
  ADD CONSTRAINT "PK_EXPERIMENTASSET" 
    PRIMARY KEY ("EXPERIMENTASSETID") 
    /*PK_TABLESPACE*/
    ENABLE;
  
  ALTER TABLE "A2_EXPERIMENTASSET" 
  ADD CONSTRAINT "FK_EXPERIMENTASSET_EXPERIMENT" 
    FOREIGN KEY ("EXPERIMENTID") 
    REFERENCES "A2_EXPERIMENT" ("EXPERIMENTID")
    ON DELETE CASCADE
    ENABLE;     
    
  CREATE INDEX "IDX_EXPERIMENTASSET_EXPERIMENT"
  ON "A2_EXPERIMENTASSET" ("EXPERIMENTID") 
  /*INDEX_TABLESPACE*/;   
    
  CREATE OR REPLACE TRIGGER A2_EXPERIMENTASSET_INSERT  
before insert on A2_EXPERIMENTASSET
for each row
begin
if(:new.EXPERIMENTASSETID is null) then
select A2_EXPERIMENTASSET_seq.nextval into :new.EXPERIMENTASSETID from dual;
end if;
end;
/

ALTER TRIGGER A2_EXPERIMENTASSET_INSERT ENABLE;  
    
--------------------------------------------------------
-- ASSAY
--------------------------------------------------------
  CREATE SEQUENCE  "A2_ASSAY_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;


  CREATE TABLE "A2_ASSAY" (
    "ASSAYID" NUMBER(22,0) CONSTRAINT NN_ASSAY_ASSAYID NOT NULL
  , "ACCESSION" VARCHAR2(255) CONSTRAINT NN_ASSAY_ACCESSION NOT NULL
  , "EXPERIMENTID" NUMBER(22,0) CONSTRAINT NN_ASSAY_EXPERIMENTID NOT NULL
  , "ARRAYDESIGNID" NUMBER(22,0) CONSTRAINT NN_ASSAY_ARRAYDESIGNID NOT NULL);    


  ALTER TABLE "A2_ASSAY" 
  ADD CONSTRAINT "PK_ASSAY" 
    PRIMARY KEY ("ASSAYID") 
    /*PK_TABLESPACE*/
    ENABLE;


  ALTER TABLE "A2_ASSAY" 
  ADD CONSTRAINT "FK_ASSAY_ARRAYDESIGN" 
    FOREIGN KEY ("ARRAYDESIGNID") 
    REFERENCES "A2_ARRAYDESIGN" ("ARRAYDESIGNID") 
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_ASSAY" 
  ADD CONSTRAINT "FK_ASSAY_EXPERIMENT" 
    FOREIGN KEY ("EXPERIMENTID") 
    REFERENCES "A2_EXPERIMENT" ("EXPERIMENTID")
    ON DELETE CASCADE
    ENABLE;  


  CREATE INDEX "IDX_ASSAY_ARRAYDESIGN"
  ON "A2_ASSAY" ("ARRAYDESIGNID")
  /*INDEX_TABLESPACE*/;  


  CREATE INDEX "IDX_ASSAY_EXPERIMENT"
  ON "A2_ASSAY" ("EXPERIMENTID") 
  /*INDEX_TABLESPACE*/;


 ALTER TABLE "A2_ASSAY" 
  ADD CONSTRAINT "UQ_ASSAY_ACCESSION" 
    UNIQUE("EXPERIMENTID","ACCESSION") 
    ENABLE;


CREATE OR REPLACE TRIGGER A2_ASSAY_INSERT  
before insert on A2_Assay
for each row
begin
if(:new.AssayID is null) then
select A2_Assay_seq.nextval into :new.AssayID from dual;
end if;
end;
/

ALTER TRIGGER A2_ASSAY_INSERT ENABLE;


--------------------------------------------------------
-- SAMPLE
--------------------------------------------------------
   CREATE SEQUENCE  "A2_SAMPLE_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;


 CREATE TABLE "A2_SAMPLE" (
    "SAMPLEID" NUMBER(22,0) CONSTRAINT NN_SAMPLE_SAMPLEID NOT NULL
  , "EXPERIMENTID" NUMBER(22,0) CONSTRAINT NN_SAMPLE_EXPERIMENTID NOT NULL
  , "ACCESSION" VARCHAR2(255) CONSTRAINT NN_SAMPLE_ACCESSION NOT NULL
  , "ORGANISMID" NUMBER(22,0)
  , "CHANNEL" VARCHAR2(255));


  ALTER TABLE "A2_SAMPLE" 
  ADD CONSTRAINT "PK_SAMPLE" 
    PRIMARY KEY ("SAMPLEID") 
  /*PK_TABLESPACE*/
  ENABLE; 

  ALTER TABLE "A2_SAMPLE"
  ADD CONSTRAINT "FK_SAMPLE_EXPERIMENT"
    FOREIGN KEY ("EXPERIMENTID")
    REFERENCES "A2_EXPERIMENT" ("EXPERIMENTID")
    ON DELETE CASCADE
    ENABLE;

CREATE INDEX "IDX_SAMPLE_EXPERIMENT"
  ON "A2_SAMPLE" (EXPERIMENTID)
  /*INDEX_TABLESPACE*/;

  ALTER TABLE "A2_SAMPLE"
  ADD CONSTRAINT "FK_SAMPLE_ORGANISM"
    FOREIGN KEY ("ORGANISMID")
    REFERENCES "A2_ORGANISM" ("ORGANISMID");

CREATE OR REPLACE TRIGGER A2_SAMPLE_INSERT
before insert on A2_Sample
for each row
begin
if(:new.SampleID is null) then
select A2_Sample_seq.nextval into :new.SampleID from dual;
end if;
end;
/

ALTER TRIGGER A2_SAMPLE_INSERT ENABLE;


--------------------------------------------------------
-- ASSAYSAMPLE
--------------------------------------------------------
 CREATE TABLE "A2_ASSAYSAMPLE" (
   "ASSAYID" NUMBER(22,0) CONSTRAINT NN_ASSAYSAMPLE_ASSAYID NOT NULL
  , "SAMPLEID" NUMBER(22,0) CONSTRAINT NN_ASSAYSAMPLE_SAMPLEID NOT NULL) ;


  ALTER TABLE "A2_ASSAYSAMPLE" 
  ADD CONSTRAINT "PK_ASSAYSAMPLE" 
    PRIMARY KEY ("ASSAYID", "SAMPLEID")
    /*PK_TABLESPACE*/
    ENABLE;   


  CREATE INDEX "IDX_ASSAYSAMPLE_ASSAY" 
  ON "A2_ASSAYSAMPLE" ("ASSAYID") 
  /*INDEX_TABLESPACE*/;


  CREATE INDEX "IDX_ASSAYSAMPLE_SAMPLE" 
  ON "A2_ASSAYSAMPLE" ("SAMPLEID") 
  /*INDEX_TABLESPACE*/;


  ALTER TABLE "A2_ASSAYSAMPLE" 
  ADD CONSTRAINT "FK_ASSAYSAMPLE_ASSAY" 
    FOREIGN KEY ("ASSAYID") 
    REFERENCES "A2_ASSAY" ("ASSAYID") 
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_ASSAYSAMPLE" 
  ADD CONSTRAINT "FK_ASSAYSAMPLE_SAMPLE" 
    FOREIGN KEY ("SAMPLEID") 
    REFERENCES "A2_SAMPLE" ("SAMPLEID") 
    ON DELETE CASCADE
    ENABLE;

--------------------------------------------------------
-- ASSAYPROPERTYVALUE
--------------------------------------------------------
   CREATE SEQUENCE  "A2_ASSAYPV_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;


  CREATE TABLE "A2_ASSAYPV" (
    "ASSAYPVID" NUMBER(22,0) CONSTRAINT NN_ASSAYPV_ID NOT NULL
  , "ASSAYID" NUMBER(22,0) CONSTRAINT NN_ASSAYPV_ASSAYID NOT NULL
  , "PROPERTYVALUEID" NUMBER(22,0) CONSTRAINT NN_ASSAYPV_PROPERTYVALUEID NOT NULL);


  ALTER TABLE "A2_ASSAYPV" 
  ADD CONSTRAINT "PK_ASSAYPV" 
    PRIMARY KEY ("ASSAYPVID") 
    /*PK_TABLESPACE*/
    ENABLE;


  CREATE INDEX "IDX_ASSAYPV_PROPERTYVALUE" 
  ON "A2_ASSAYPV" ("PROPERTYVALUEID") 
  /*INDEX_TABLESPACE*/;


  CREATE INDEX "IDX_ASSAYPV_ASSAY" 
  ON "A2_ASSAYPV" ("ASSAYID") 
  /*INDEX_TABLESPACE*/;


  CREATE INDEX "IDX_ASSAYPV_AP" 
  ON "A2_ASSAYPV" ("ASSAYID", "PROPERTYVALUEID") 
  /*INDEX_TABLESPACE*/; --composite index


  ALTER TABLE "A2_ASSAYPV" 
  ADD CONSTRAINT "FK_ASSAYPV_PROPERTY" 
    FOREIGN KEY ("PROPERTYVALUEID") 
    REFERENCES "A2_PROPERTYVALUE" ("PROPERTYVALUEID") 
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_ASSAYPV" 
  ADD CONSTRAINT "FK_ASSAYPV_ASSAY" 
    FOREIGN KEY ("ASSAYID") 
    REFERENCES "A2_ASSAY" ("ASSAYID") 
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_ASSAYPV" 
  ADD CONSTRAINT "UQ_ASSAYPV" 
    UNIQUE(ASSAYID, PropertyValueID) 
    ENABLE;  


CREATE OR REPLACE TRIGGER A2_ASSAYPV_INSERT  
before insert on A2_ASSAYPV
for each row
begin
if(:new.ASSAYPVID is null) then
select A2_ASSAYPV_seq.nextval into :new.ASSAYPVID from dual;
end if;
end;
/

ALTER TRIGGER A2_ASSAYPV_INSERT ENABLE;

--------------------------------------------------------
-- SAMPLEPROPERTYVALUE
--------------------------------------------------------
 CREATE SEQUENCE  "A2_SAMPLEPV_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;


  CREATE TABLE "A2_SAMPLEPV" (
    "SAMPLEPVID" NUMBER(22,0) CONSTRAINT NN_SAMPLEPV_ID NOT NULL
  , "SAMPLEID" NUMBER(22,0) CONSTRAINT NN_SAMPLEPV_SAMPLEID NOT NULL
  , "PROPERTYVALUEID" NUMBER(22,0) CONSTRAINT NN_SAMPLEPV_PROPERTYVALUEID NOT NULL);


 ALTER TABLE "A2_SAMPLEPV" 
  ADD CONSTRAINT "PK_SAMPLEPV" 
    PRIMARY KEY ("SAMPLEPVID") 
  /*PK_TABLESPACE*/
  ENABLE; 


  CREATE INDEX "IDX_SAMPLEPROPERTY_PROPERTY" 
  ON "A2_SAMPLEPV" ("PROPERTYVALUEID") 
  /*INDEX_TABLESPACE*/;


  CREATE INDEX "IDX_SAMPLEPROPERTY_PS" 
  ON "A2_SAMPLEPV" ("PROPERTYVALUEID", "SAMPLEID") 
  /*INDEX_TABLESPACE*/;


  CREATE INDEX "IDX_SAMPLEPROPERTY_SAMPLE" 
  ON "A2_SAMPLEPV" ("SAMPLEID") 
  /*INDEX_TABLESPACE*/;


  CREATE INDEX "IDX_SAMPLEPROPERTY_SP" 
  ON "A2_SAMPLEPV" ("SAMPLEID", "PROPERTYVALUEID") 
  /*INDEX_TABLESPACE*/;


  ALTER TABLE "A2_SAMPLEPV" 
  ADD CONSTRAINT "FK_SAMPLEPROPERTY_SAMPLE" 
    FOREIGN KEY ("SAMPLEID") 
    REFERENCES "A2_SAMPLE" ("SAMPLEID") 
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_SAMPLEPV" 
  ADD CONSTRAINT "FK_SAMPLEPROPERTY_PROPERTY" 
    FOREIGN KEY ("PROPERTYVALUEID") 
    REFERENCES "A2_PROPERTYVALUE" ("PROPERTYVALUEID") 
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_SAMPLEPV" 
  ADD CONSTRAINT "UQ_SAMPLEPV" 
    UNIQUE(SAMPLEID, PropertyValueID) 
    ENABLE; 


CREATE OR REPLACE TRIGGER A2_SAMPLEPV_INSERT  
before insert on A2_SAMPLEPV
for each row
begin
if(:new.SAMPLEPVID is null) then
select A2_SAMPLEPV_seq.nextval into :new.SAMPLEPVID from dual;
end if;
end;
/

ALTER TRIGGER A2_SAMPLEPV_INSERT ENABLE;   

--------------------------------------------------------
-- ONTOLOGY
--------------------------------------------------------

CREATE SEQUENCE "A2_ONTOLOGY_SEQ";

  CREATE TABLE "A2_ONTOLOGY" (
    "ONTOLOGYID" NUMBER(22,0) CONSTRAINT NN_ONTOLOGY_ID NOT NULL
  , "NAME" VARCHAR2(255) 
  , "SOURCE_URI" VARCHAR2(500)
  , "DESCRIPTION" VARCHAR2(4000)
  , "VERSION" VARCHAR2(50));


  ALTER TABLE "A2_ONTOLOGY" 
  ADD CONSTRAINT "PK_ONTOLOGY" 
    PRIMARY KEY ("ONTOLOGYID") 
    /*PK_TABLESPACE*/
    ENABLE;

CREATE OR REPLACE TRIGGER A2_ONTOLOGY_INSERT
before insert on A2_Ontology
for each row
begin
if( :new.OntologyID is null) then
select A2_Ontology_seq.nextval into :new.OntologyID from dual;
end if;
end;
/

ALTER TRIGGER A2_ONTOLOGY_INSERT ENABLE;

--------------------------------------------------------
-- ONTOLOGY TERM
--------------------------------------------------------
CREATE SEQUENCE  "A2_ONTOLOGYTERM_SEQ"  
    MINVALUE 1 MAXVALUE 1.00000000000000E+27 
    INCREMENT BY 1 START WITH 1 CACHE 20 
    NOORDER  NOCYCLE;


CREATE TABLE "A2_ONTOLOGYTERM" (
    "ONTOLOGYTERMID" NUMBER(22,0) CONSTRAINT NN_ONTOLOGYTERM_ID NOT NULL
  , "ONTOLOGYID" NUMBER(22,0) CONSTRAINT NN_ONTOLOGYTERM_ONTOLOGYID NOT NULL
  , "TERM" VARCHAR2(4000)
  , "ACCESSION" VARCHAR2(255) CONSTRAINT NN_ONTOLOGYTERM_ACCESSION NOT NULL
  , "DESCRIPTION" VARCHAR2(4000));


 ALTER TABLE "A2_ONTOLOGYTERM" 
  ADD CONSTRAINT "PK_ONTOLOGYTERM" 
    PRIMARY KEY ("ONTOLOGYTERMID") 
    /*PK_TABLESPACE*/
    ENABLE;


  CREATE INDEX "IDX_ONTOLOGYTERM_ONTOLOGY" 
  ON "A2_ONTOLOGYTERM" ("ONTOLOGYID") 
  /*INDEX_TABLESPACE*/;   


  ALTER TABLE "A2_ONTOLOGYTERM" 
  ADD CONSTRAINT "FK_ONTOLOGYTERM_ONTOLOGY" 
    FOREIGN KEY ("ONTOLOGYID") 
    REFERENCES "A2_ONTOLOGY" ("ONTOLOGYID") 
    ON DELETE CASCADE
    ENABLE;


 ALTER TABLE "A2_ONTOLOGYTERM" 
  ADD CONSTRAINT "UQ_ONTOLOGYTERM_ACCESSION" 
    UNIQUE(ONTOLOGYID, "ACCESSION") 
    ENABLE;   


CREATE OR REPLACE TRIGGER A2_ONTOLOGYTERM_INSERT  
before insert on A2_OntologyTerm
for each row
begin
if( :new.OntologyTermID is null) then
select A2_OntologyTerm_seq.nextval into :new.OntologyTermID from dual;
end if;
end;
/

ALTER TRIGGER A2_ONTOLOGYTERM_INSERT ENABLE; 


--------------------------------------------------------
-- ASSAYPROPERTYVALUEONTOLOGY 
--------------------------------------------------------
  CREATE TABLE "A2_ASSAYPVONTOLOGY" (
    "ONTOLOGYTERMID" NUMBER(22,0) CONSTRAINT NN_ASSAYPVONTOLOGY_OTID NOT NULL
  , "ASSAYPVID" NUMBER(22,0) CONSTRAINT NN_ASSAYPVONTOLOGY_ASSAYPVID NOT NULL);


  ALTER TABLE "A2_ASSAYPVONTOLOGY"
  ADD CONSTRAINT "PK_ASSAYPVONTOLOGY" 
    PRIMARY KEY ("ONTOLOGYTERMID", "ASSAYPVID")
    /*PK_TABLESPACE*/
    ENABLE;


  ALTER TABLE "A2_ASSAYPVONTOLOGY" 
  ADD CONSTRAINT "FK_ASSAYPVONTOLOGY_ASSAYPV" 
    FOREIGN KEY ("ASSAYPVID") 
    REFERENCES "A2_ASSAYPV" ("ASSAYPVID") 
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_ASSAYPVONTOLOGY" 
  ADD CONSTRAINT "FK_ASSAYPVONTOLOGY_ONTOLOGY" 
    FOREIGN KEY ("ONTOLOGYTERMID") 
    REFERENCES "A2_ONTOLOGYTERM" ("ONTOLOGYTERMID") 
    ON DELETE CASCADE
    ENABLE;  

--------------------------------------------------------
-- SAMPLEPROPERTYVALUEONTOLOGY 
--------------------------------------------------------

  CREATE TABLE "A2_SAMPLEPVONTOLOGY" (
    "ONTOLOGYTERMID" NUMBER(22,0) CONSTRAINT NN_SAMPLEPVONTOLOGY_OTID NOT NULL
  , "SAMPLEPVID" NUMBER(22,0) CONSTRAINT NN_SAMPLEPVONTOLOGY_SAMPLEPVID NOT NULL);    


  ALTER TABLE "A2_SAMPLEPVONTOLOGY" 
  ADD CONSTRAINT "PK_SAMPLEPVONTOLOGY" 
    PRIMARY KEY ("ONTOLOGYTERMID", "SAMPLEPVID")
  /*PK_TABLESPACE*/
  ENABLE;   


  ALTER TABLE "A2_SAMPLEPVONTOLOGY"
  ADD CONSTRAINT "FK_SAMPLEPVONTOLOGY_SAMPLEPV" 
    FOREIGN KEY ("SAMPLEPVID") 
    REFERENCES "A2_SAMPLEPV" ("SAMPLEPVID") 
    ON DELETE CASCADE
    ENABLE;

  ALTER TABLE "A2_SAMPLEPVONTOLOGY" 
  ADD CONSTRAINT "FK_SAMPLEPVONTOLOGY_ONTOLOGY" 
    FOREIGN KEY ("ONTOLOGYTERMID") 
    REFERENCES "A2_ONTOLOGYTERM" ("ONTOLOGYTERMID") 
    ON DELETE CASCADE
    ENABLE;

--------------------------------------------------------
-- BIOENTITY PROPERTY
--------------------------------------------------------
 CREATE SEQUENCE  "A2_BIOENTITYPROPERTY_SEQ"
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;


  CREATE TABLE "A2_BIOENTITYPROPERTY" (
    "BIOENTITYPROPERTYID" NUMBER(22,0)  CONSTRAINT NN_BIOENTITYPROPERTY_ID NOT NULL
  , "NAME" VARCHAR2(255) CONSTRAINT NN_BIOENTITYPROPERTY_NAME NOT NULL
  );


  ALTER TABLE "A2_BIOENTITYPROPERTY"
  ADD CONSTRAINT "PK_BIOENTITYPROPERTY"
    PRIMARY KEY ("BIOENTITYPROPERTYID")
    /*PK_TABLESPACE*/
    ENABLE;


  ALTER TABLE "A2_BIOENTITYPROPERTY"
  ADD CONSTRAINT "UQ_BIOENTITYPROPERTY_NAME"
    UNIQUE("NAME")
    ENABLE;


CREATE OR REPLACE TRIGGER A2_BIOENTITYPROPERTY_INSERT
before insert on A2_BIOENTITYProperty
for each row
begin
if(:new.BIOENTITYPropertyID is null) then
select A2_BIOENTITYProperty_seq.nextval into :new.BIOENTITYPropertyID from dual;
end if;
end;
/

ALTER TRIGGER A2_BIOENTITYProperty_INSERT ENABLE;

--------------------------------------------------------
-- BIOENTITY PROPERTYVALUE
--------------------------------------------------------
 CREATE SEQUENCE  "A2_BIOENTITYPROPERTYVALUE_SEQ"
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;


  CREATE TABLE "A2_BIOENTITYPROPERTYVALUE" (
    "BEPROPERTYVALUEID" NUMBER(22,0) CONSTRAINT NN_BEPV_ID NOT NULL
  , "BIOENTITYPROPERTYID" NUMBER(22,0) CONSTRAINT NN_GPV_BEPROPERTYID NOT NULL
  , "VALUE" VARCHAR2(1000) CONSTRAINT NN_BEPV_VALUE NOT NULL);


  ALTER TABLE "A2_BIOENTITYPROPERTYVALUE"
  ADD CONSTRAINT "PK_BEPROPERTYVALUE"
    PRIMARY KEY ("BEPROPERTYVALUEID")
    /*PK_TABLESPACE*/
    ENABLE;


  CREATE INDEX "IDX_BEPROPERTYVALUEID_PROPERTY"
  ON "A2_BIOENTITYPROPERTYVALUE" ("BIOENTITYPROPERTYID")
  /*INDEX_TABLESPACE*/;


  ALTER TABLE "A2_BIOENTITYPROPERTYVALUE"
  ADD CONSTRAINT "FK_BEPROPERTYVALUE_PROPERTY"
    FOREIGN KEY ("BIOENTITYPROPERTYID")
    REFERENCES "A2_BIOENTITYPROPERTY" ("BIOENTITYPROPERTYID")
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_BIOENTITYPROPERTYVALUE"
  ADD CONSTRAINT "UQ_BEPROPERTYVALUE_VALUE"
    UNIQUE("BIOENTITYPROPERTYID","VALUE")
    ENABLE;

CREATE OR REPLACE TRIGGER A2_BEPROPERTYVALUE_INSERT
before insert on A2_BIOENTITYPropertyValue
for each row
begin
if(:new.BEPropertyValueID is null) then
select A2_BIOENTITYPROPERTYVALUE_SEQ.nextval into :new.BEPropertyValueID from dual;
end if;
end;
/

ALTER TRIGGER A2_BEPROPERTYVALUE_INSERT ENABLE;

--------------------------------------------------------
-- BIOENTITYTYPE
--------------------------------------------------------
 CREATE SEQUENCE  "A2_BIOENTITYTYPE_SEQ"
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;


 CREATE TABLE "A2_BIOENTITYTYPE" (
    "BIOENTITYTYPEID" NUMBER(22,0) CONSTRAINT NN_BIOENTITYTYPEID_ID NOT NULL
  , "NAME" VARCHAR2(255) CONSTRAINT NN_BETYPE_NAME NOT NULL
  , "ID_FOR_INDEX" VARCHAR2(1) default '0'
  , "ID_FOR_ANALYTICS" VARCHAR2(1) default '0'
  , "IDENTIFIERPROPERTYID" NUMBER(22,0)
  , "NAMEPROPERTYID" NUMBER(22,0)
  , "PROP_FOR_INDEX" VARCHAR2(1) default '0');


  ALTER TABLE "A2_BIOENTITYTYPE"
  ADD CONSTRAINT "PK_BIOENTITYTYPE"
    PRIMARY KEY ("BIOENTITYTYPEID")
    /*PK_TABLESPACE*/
    ENABLE;

 ALTER TABLE "A2_BIOENTITYTYPE"
  ADD CONSTRAINT "UQ_BIOENTITYTYPE_NAME"
    UNIQUE("NAME")
    ENABLE;


CREATE OR REPLACE TRIGGER A2_BIOENTITYTYPE_INSERT
before insert on A2_BIOENTITYTYPE
for each row
begin
if(:new.BIOENTITYTYPEID is null) then
select A2_BIOENTITYTYPE_seq.nextval into :new.BIOENTITYTYPEID from dual;
end if;
end;
/

ALTER TRIGGER A2_BIOENTITYTYPE_INSERT ENABLE;

--------------------------------------------------------
-- BIOENTITY
--------------------------------------------------------
 CREATE SEQUENCE  "A2_BIOENTITY_SEQ"
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;


 CREATE TABLE "A2_BIOENTITY" (
    "BIOENTITYID" NUMBER(22,0) CONSTRAINT NN_BIOENTITY_ID NOT NULL
  , "IDENTIFIER" VARCHAR2(255) CONSTRAINT NN_BIOENTITY_IDENTIFIER NOT NULL
  , "NAME" VARCHAR2(255)
  , "ORGANISMID" NUMBER(22,0) CONSTRAINT NN_BIOENTITY_ORGANISMID NOT NULL
  , "BIOENTITYTYPEID" NUMBER(22,0) CONSTRAINT NN_BIOENTITY_BIOENTITYTYPEID NOT NULL);


  ALTER TABLE "A2_BIOENTITY"
  ADD CONSTRAINT "PK_BIOENTITY"
    PRIMARY KEY ("BIOENTITYID")
    /*PK_TABLESPACE*/
    ENABLE;


  CREATE INDEX "IDX_BIOENTITY_ORGANISM"
  ON "A2_BIOENTITY" ("ORGANISMID")
  /*INDEX_TABLESPACE*/;


  ALTER TABLE "A2_BIOENTITY"
  ADD CONSTRAINT "FK_BIOENTITY_ORGANISM"
    FOREIGN KEY ("ORGANISMID")
    REFERENCES "A2_ORGANISM" ("ORGANISMID")
    ON DELETE CASCADE
    ENABLE;

  CREATE INDEX "IDX_BIOENTITY_BIOENTITYTYPEID"
  ON "A2_BIOENTITY" ("BIOENTITYTYPEID")
  /*INDEX_TABLESPACE*/;


  ALTER TABLE "A2_BIOENTITY"
  ADD CONSTRAINT "FK_BIOENTITY_BIOENTITYTYPE"
    FOREIGN KEY ("BIOENTITYTYPEID")
    REFERENCES "A2_BIOENTITYTYPE" ("BIOENTITYTYPEID")
    ON DELETE CASCADE
    ENABLE;

 ALTER TABLE "A2_BIOENTITY"
  ADD CONSTRAINT "UQ_BIOENTITY_ID_TYPE"
    UNIQUE("IDENTIFIER", "BIOENTITYTYPEID")
    ENABLE;


CREATE OR REPLACE TRIGGER A2_BIOENTITY_INSERT
before insert on A2_BIOENTITY
for each row
begin
if(:new.BIOENTITYID is null) then
select A2_BIOENTITY_seq.nextval into :new.BIOENTITYID from dual;
end if;

if(:new.OrganismID is null) then
select OrganismID into :new.OrganismID from a2_Organism where Name = 'unknown';
end if;

end;
/

ALTER TRIGGER A2_BIOENTITY_INSERT ENABLE;

--------------------------------------------------------
-- BERELATIONTYPE
--------------------------------------------------------
 CREATE SEQUENCE  "A2_BERELATIONTYPE_SEQ"
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;


 CREATE TABLE "A2_BERELATIONTYPE" (
    "BERELATIONTYPEID" NUMBER(22,0) CONSTRAINT NN_BERELATIONTYPEID_ID NOT NULL
  , "NAME" VARCHAR2(255) CONSTRAINT NN_BERELATIONTYPE_NAME NOT NULL )
 ;

  ALTER TABLE "A2_BERELATIONTYPE"
  ADD CONSTRAINT "PK_BERELATIONTYPE"
    PRIMARY KEY ("BERELATIONTYPEID")
    /*PK_TABLESPACE*/
    ENABLE;

 ALTER TABLE "A2_BERELATIONTYPE"
  ADD CONSTRAINT "UQ_BERELATIONTYPE_NAME"
    UNIQUE("NAME")
    ENABLE;


CREATE OR REPLACE TRIGGER A2_BERELATIONTYPE_INSERT
before insert on A2_BERELATIONTYPE
for each row
begin
if(:new.BERELATIONTYPEID is null) then
select A2_BERELATIONTYPE_seq.nextval into :new.BERELATIONTYPEID from dual;
end if;
end;
/

ALTER TRIGGER A2_BERELATIONTYPE_INSERT ENABLE;

--------------------------------------------------------
-- BIOENTITY BIOENTITYPROPERTYVALUE
--------------------------------------------------------
  CREATE SEQUENCE  "A2_BIOENTITYBEPV_SEQ"
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;


  CREATE TABLE "A2_BIOENTITYBEPV" (
    "BIOENTITYBEPVID" NUMBER(22,0) CONSTRAINT NN_BIOENTITYBEPV_ID NOT NULL
  , "BIOENTITYID" NUMBER(22,0)  CONSTRAINT NN_BIOENTITYBEPV_BIOENTITYID NOT NULL
  , "BEPROPERTYVALUEID" NUMBER(22,0)  CONSTRAINT NN_BIOENTITYBEPV_BEPVID NOT NULL
  , "SOFTWAREID" NUMBER(22,0)  CONSTRAINT NN_BIOENTITYBEPV_SWID NOT NULL);


  ALTER TABLE "A2_BIOENTITYBEPV"
  ADD CONSTRAINT "PK_BIOENTITYBEPV"
    PRIMARY KEY ("BIOENTITYBEPVID")
    /*PK_TABLESPACE*/
    ENABLE;


  CREATE INDEX "IDX_BIOENTITYBEPV_ASSOCIATION"
  ON "A2_BIOENTITYBEPV" (BIOENTITYID, SOFTWAREID, bepropertyvalueid)
  /*INDEX_TABLESPACE*/;

  ALTER TABLE "A2_BIOENTITYBEPV"
  ADD CONSTRAINT "FK_BIOENTITYBEPV_BIOENTITY"
    FOREIGN KEY ("BIOENTITYID")
    REFERENCES "A2_BIOENTITY" ("BIOENTITYID")
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_BIOENTITYBEPV"
  ADD CONSTRAINT "FK_BIOENTITYBEPV_BIOENTITYPV"
    FOREIGN KEY ("BEPROPERTYVALUEID")
    REFERENCES "A2_BIOENTITYPROPERTYVALUE" ("BEPROPERTYVALUEID")
    ON DELETE CASCADE
    ENABLE;

  ALTER TABLE "A2_BIOENTITYBEPV"
  ADD CONSTRAINT "FK_BIOENTITYBEPV_SOFTWARE"
    FOREIGN KEY ("SOFTWAREID")
    REFERENCES "A2_SOFTWARE" ("SOFTWAREID")
    ON DELETE CASCADE
    ENABLE;

  ALTER TABLE "A2_BIOENTITYBEPV"
  ADD CONSTRAINT "UQ_BIOENTITY_BEPV_SW"
    UNIQUE("BIOENTITYID","BEPROPERTYVALUEID", "SOFTWAREID")
    ENABLE;


CREATE OR REPLACE TRIGGER A2_BIOENTITYBEPV_INSERT
before insert on A2_BIOENTITYBEPV
for each row
begin
if(:new.BIOENTITYBEPVID is null) then
select A2_BIOENTITYBEPV_seq.nextval into :new.BIOENTITYBEPVID from dual;
end if;
end;
/

ALTER TRIGGER A2_BIOENTITYBEPV_INSERT ENABLE;

--------------------------------------------------------
-- DESIGNELEMENT BIOENTITY
--------------------------------------------------------
  CREATE SEQUENCE  "A2_DESIGNELTBIOENTITY_SEQ"
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;


  CREATE TABLE "A2_DESIGNELTBIOENTITY" (
    "DEBEID" NUMBER(22,0) CONSTRAINT NN_DEBE_ID NOT NULL
  , "DESIGNELEMENTID" NUMBER(22,0) CONSTRAINT NN_DEBE_DESIGNELEMENTID NOT NULL
  , "BIOENTITYID" NUMBER(22,0)  CONSTRAINT NN_DEBE_BIOENTITYID NOT NULL
  , "SOFTWAREID" NUMBER(22,0)  CONSTRAINT NN_DEBE_SOFTWAREID NOT NULL);


  ALTER TABLE "A2_DESIGNELTBIOENTITY"
  ADD CONSTRAINT "PK_DESIGNELTBIOENTITY"
    PRIMARY KEY ("DEBEID")
    /*PK_TABLESPACE*/
    ENABLE;

CREATE INDEX "IDX_DESIGNELTBIOENTITY_ASS"
  ON A2_DESIGNELTBIOENTITY (DESIGNELEMENTID, BIOENTITYID)
  /*INDEX_TABLESPACE*/;


  ALTER TABLE "A2_DESIGNELTBIOENTITY"
  ADD CONSTRAINT "FK_DEBE_BIOENTITY"
    FOREIGN KEY ("BIOENTITYID")
    REFERENCES "A2_BIOENTITY" ("BIOENTITYID")
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_DESIGNELTBIOENTITY"
  ADD CONSTRAINT "FK_DEBE_DESIGNELEMENT"
    FOREIGN KEY ("DESIGNELEMENTID")
    REFERENCES "A2_DESIGNELEMENT" ("DESIGNELEMENTID")
    ON DELETE CASCADE
    ENABLE;


  ALTER TABLE "A2_DESIGNELTBIOENTITY"
  ADD CONSTRAINT "UQ_DESIGNELTBIOENTITY"
    UNIQUE("BIOENTITYID","DESIGNELEMENTID", "SOFTWAREID")
    ENABLE;


CREATE OR REPLACE TRIGGER A2_DESIGNELTBIOENTITY_INSERT
before insert on A2_DESIGNELTBIOENTITY
for each row
begin
if(:new.DEBEID is null) then
select A2_DESIGNELTBIOENTITY_seq.nextval into :new.DEBEID from dual;
end if;
end;
/

ALTER TRIGGER A2_DESIGNELTBIOENTITY_INSERT ENABLE;

CREATE BITMAP INDEX "IDX_BIOENTITYBEPV_BEID_SWID"
ON "A2_BIOENTITYBEPV" (BIOENTITYID, SOFTWAREID)
/*INDEX_TABLESPACE*/;

--------------------------------------------------------
--  DDL for TEMP TABLE
--------------------------------------------------------

create global temporary table tmp_DesignElementMap(
    DesignElementAccession varchar2(255) NOT NULL
    ,GeneID NUMBER(22,0) 
    ,GeneIdentifier varchar2(255)) ON COMMIT DELETE ROWS;

    
--------------------------------------------------------
--  TASK MANAGER DATA STRUCTURES
--------------------------------------------------------  

CREATE TABLE A2_TASKMAN_LOG
(
  ID NUMBER NOT NULL,
  TASKID NUMBER NOT NULL,
  TYPE VARCHAR2(32) NOT NULL,
  ACCESSION VARCHAR2(256 CHAR)  NOT NULL,
  RUNMODE VARCHAR2(32),
  USERNAME VARCHAR2(64) NOT NULL,
  EVENT VARCHAR2(32) NOT NULL,
  MESSAGE VARCHAR2(4000 CHAR),
  TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL -- NOT NULL DEFAULT SYSTIMESTAMP does not work.
, CONSTRAINT A2_TASKMAN_LOG_PK PRIMARY KEY
  (
    ID
  )
);

CREATE SEQUENCE A2_TASKMAN_TASKID_SEQ ;

CREATE INDEX A2_TASKMAN_LOG_IDX1 ON A2_TASKMAN_LOG (TYPE, ACCESSION) NOPARALLEL /*INDEX_TABLESPACE*/;

CREATE INDEX A2_TASKMAN_LOG_IDX2 ON A2_TASKMAN_LOG (TASKID) NOPARALLEL /*INDEX_TABLESPACE*/;

CREATE INDEX A2_TASKMAN_LOG_IDX3 ON A2_TASKMAN_LOG (USERNAME) NOPARALLEL /*INDEX_TABLESPACE*/;

CREATE INDEX A2_TASKMAN_LOG_IDX4 ON A2_TASKMAN_LOG (TYPE) NOPARALLEL /*INDEX_TABLESPACE*/;

CREATE INDEX A2_TASKMAN_LOG_IDX5 ON A2_TASKMAN_LOG (EVENT) NOPARALLEL /*INDEX_TABLESPACE*/;

CREATE SEQUENCE A2_TASKMAN_LOG_SEQ ;

CREATE
TRIGGER A2_TASKMAN_LOG_TRG
 BEFORE INSERT ON A2_TASKMAN_LOG
FOR EACH ROW 
BEGIN
  SELECT A2_TASKMAN_LOG_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/

CREATE TABLE A2_TASKMAN_STATUS
(
  TYPE VARCHAR2(32)NOT NULL,
  ACCESSION VARCHAR2(256 CHAR) NOT NULL,
  STATUS VARCHAR2(32) NOT NULL
, CONSTRAINT A2_TASKMAN_TASKSTATUS_PK PRIMARY KEY
  (
    TYPE,
    ACCESSION
  )
);

 CREATE TABLE A2_TASKMAN_TAGTASKS
 (
    TASKCLOUDID NUMBER NOT NULL,
    TASKID NUMBER NOT NULL,
    PRIMARY KEY (TASKCLOUDID, TASKID)
 );


 CREATE TABLE A2_TASKMAN_TAG
 (
    TASKCLOUDID NUMBER NOT NULL,
    TAG VARCHAR2(512 CHAR) NOT NULL,
    TAGTYPE VARCHAR2(32 CHAR) NOT NULL,
    PRIMARY KEY (TASKCLOUDID, TAGTYPE, TAG)
 );
 
 CREATE INDEX A2_TASKMAN_TAG_IDX1 ON A2_TASKMAN_TAG (TAGTYPE, TAG) NOPARALLEL /*INDEX_TABLESPACE*/;
 
 CREATE INDEX A2_TASKMAN_TAG_IDX2 ON A2_TASKMAN_TAG (TAGTYPE) NOPARALLEL /*INDEX_TABLESPACE*/;
 

CREATE TABLE A2_CONFIG_PROPERTY
(
  NAME VARCHAR2(128 CHAR) CONSTRAINT NN_CONFIGPROP_NAME NOT NULL,
  VALUE VARCHAR2(4000 CHAR)
, CONSTRAINT A2_CONFIG_PROPERTIES_PK PRIMARY KEY
  (
    NAME
  )
);

-------------------------------------------------------------------------------
-- Curators comments
-- drop table A2_EXPERIMENTLOG
-------------------------------------------------------------------------------
CREATE SEQUENCE A2_EXPERIMENTLOG_SEQ ;

CREATE TABLE A2_EXPERIMENTLOG
(
  EXPERIMENTLOGID NUMBER CONSTRAINT NN_EXPERIMENTLOG_ID NOT NULL
, EXPERIMENTID NUMBER NOT NULL
, TYPE VARCHAR2(32) NOT NULL ---"curated"/"uncurated"
, MESSAGE VARCHAR2(4000 CHAR)
, TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
, USERNAME varchar(255)
, CONSTRAINT A2_EXPERIMENTLOG PRIMARY KEY
  (
    EXPERIMENTLOGID
  )
);

ALTER TABLE "A2_EXPERIMENTLOG" 
ADD CONSTRAINT "FK_EXPERIMENTLOG_EXPERIMENT" 
  FOREIGN KEY ("EXPERIMENTID") 
  REFERENCES "A2_EXPERIMENT" ("EXPERIMENTID")
  ON DELETE CASCADE
  ENABLE;


CREATE INDEX A2_EXPERIMENTLOG_IDX1 ON A2_EXPERIMENTLOG (EXPERIMENTID,TYPE) /*INDEX_TABLESPACE*/;

CREATE
TRIGGER A2_EXPERIMENTLOG_TRG
 BEFORE INSERT ON A2_EXPERIMENTLOG
FOR EACH ROW 
BEGIN
  SELECT A2_EXPERIMENTLOG_SEQ.NEXTVAL INTO :NEW.EXPERIMENTLOGID FROM DUAL;
END;
/

CREATE TABLE A2_SCHEMAVERSION (
  VERSION VARCHAR2(32 BYTE) NOT NULL PRIMARY KEY
, APPLIED_ON TIMESTAMP(6) NOT NULL
, DURATION NUMBER(*, 0) NOT NULL
);

-- AnnotationSource table
CREATE SEQUENCE  A2_ANNOTATIONSRC_SEQ
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;

CREATE TABLE A2_ANNOTATIONSRC(
  annotationsrcid NUMBER(22,0)  CONSTRAINT NN_ANNOTATIONSRC_ID NOT NULL
  , SOFTWAREID NUMBER(22,0)  CONSTRAINT NN_ANNOTATIONSRC_SWID NOT NULL
  , ORGANISMID NUMBER(22,0) CONSTRAINT NN_ANNOTATIONSRC_ORGANISM NOT NULL
  , url VARCHAR2(512)
  , biomartorganismname VARCHAR2(255)
  , databaseName VARCHAR2(255)
  , mySqlDbName VARCHAR2(255)
  , mySqlDbUrl VARCHAR2(255)
  , annsrctype VARCHAR2(255) CONSTRAINT NN_ANNOTATIONSRC_ASTYPE NOT NULL
  , LOADDATE DATE
  , isApplied VARCHAR2(1) DEFAULT 'F'
);

ALTER TABLE A2_ANNOTATIONSRC
  ADD CONSTRAINT PK_ANNOTATIONSRC
    PRIMARY KEY (annotationsrcid)
  ENABLE;

ALTER TABLE A2_ANNOTATIONSRC
  ADD CONSTRAINT FK_ANNOTATIONSRC_ORGANISM
    FOREIGN KEY (ORGANISMID)
    REFERENCES A2_ORGANISM (ORGANISMID)
    ON DELETE CASCADE
    ENABLE;

ALTER TABLE A2_ANNOTATIONSRC
  ADD CONSTRAINT UQ_ANNSRC_NAME_V_ORG_TYPE
    UNIQUE(SOFTWAREID, ANNSRCTYPE, ORGANISMID)
    ENABLE;

ALTER TABLE "A2_ANNOTATIONSRC"
  ADD CONSTRAINT "FK_ANNSRC_SOFTWARE"
    FOREIGN KEY ("SOFTWAREID")
    REFERENCES "A2_SOFTWARE" ("SOFTWAREID")
    ON DELETE CASCADE
    ENABLE;

CREATE OR REPLACE TRIGGER A2_ANNOTATIONSRC_INSERT
before insert on A2_ANNOTATIONSRC
for each row
begin
if(:new.annotationsrcid is null) then
select A2_ANNOTATIONSRC_SEQ.nextval into :new.annotationsrcid from dual;
end if;
END;
/

-- Link table AnnotationSource to BioEntity type
CREATE TABLE A2_ANNSRC_BIOENTITYTYPE(
  annotationsrcid NUMBER(22,0) CONSTRAINT NN_ANNSRCBET_ANNSRCID NOT NULL
  , BIOENTITYTYPEID NUMBER(22,0) CONSTRAINT NN_ANNSRCBET_BETID NOT NULL
  );

ALTER TABLE A2_ANNSRC_BIOENTITYTYPE
  ADD CONSTRAINT UQ_ANNSRCBETYPE_AS_BET
    UNIQUE(annotationsrcid, BIOENTITYTYPEID)
    ENABLE;

ALTER TABLE A2_ANNSRC_BIOENTITYTYPE
  ADD CONSTRAINT FK_A2_ANNSRCBETYPE_BETYPE
    FOREIGN KEY (BIOENTITYTYPEID)
    REFERENCES A2_BIOENTITYTYPE (BIOENTITYTYPEID)
    ON DELETE CASCADE
    ENABLE;

ALTER TABLE A2_ANNSRC_BIOENTITYTYPE
  ADD CONSTRAINT FK_ANNSRCBETYPE_ANNSRC
    FOREIGN KEY (annotationsrcid)
    REFERENCES A2_ANNOTATIONSRC (annotationsrcid)
    ON DELETE CASCADE
    ENABLE;

-- BioMart Property table
CREATE SEQUENCE  A2_BIOMARTPROPERTY_SEQ
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;

CREATE TABLE A2_BIOMARTPROPERTY (
 biomartpropertyId NUMBER(22,0) CONSTRAINT NN_BMPROPERTY_ID NOT NULL
, BIOENTITYPROPERTYID NUMBER(22,0) CONSTRAINT NN_BMPROPERTY_BEPROPERTYID NOT NULL
, NAME VARCHAR2(255) CONSTRAINT NN_BMPROPERTY_NAME NOT NULL
, annotationsrcid NUMBER(22,0) CONSTRAINT NN_BMPROPERTY_ANNSRCID NOT NULL
);

ALTER TABLE A2_BIOMARTPROPERTY
  ADD CONSTRAINT PK_BMPROPERTY
    PRIMARY KEY (biomartpropertyId)
  ENABLE;

ALTER TABLE A2_BIOMARTPROPERTY
  ADD CONSTRAINT FK_BIOMARTPROPERTY_PROPERTY
    FOREIGN KEY (BIOENTITYPROPERTYID)
    REFERENCES A2_BIOENTITYPROPERTY (BIOENTITYPROPERTYID)
    ON DELETE CASCADE
    ENABLE;

ALTER TABLE A2_BIOMARTPROPERTY
  ADD CONSTRAINT FK_BIOMARTPROPERTY_ANNSRC
    FOREIGN KEY (annotationsrcid)
    REFERENCES A2_ANNOTATIONSRC (annotationsrcid)
    ON DELETE CASCADE
    ENABLE;

ALTER TABLE A2_BIOMARTPROPERTY
  ADD CONSTRAINT UQ_BMPROP_ANNSRCID_NAME_BEPROP
    UNIQUE(annotationsrcid, NAME, BIOENTITYPROPERTYID)
    ENABLE;

CREATE OR REPLACE TRIGGER A2_BIOMARTPROPERTY_INSERT
before insert on A2_BIOMARTPROPERTY
for each row
begin
if(:new.biomartpropertyId is null) then
select A2_BIOMARTPROPERTY_SEQ.nextval into :new.biomartpropertyId from dual;
end if;
END;
/
-- BioMart ArrayDesign table
CREATE SEQUENCE  A2_BIOMARTARRAYDESIGN_SEQ
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;

CREATE TABLE A2_BIOMARTARRAYDESIGN (
 BIOMARTARRAYDESIGNID NUMBER(22,0) CONSTRAINT NN_BMAD_ID NOT NULL
, ARRAYDESIGNID NUMBER(22,0) CONSTRAINT NN_BMAD_ARAYDESIGNID NOT NULL
, NAME VARCHAR2(255) CONSTRAINT NN_BMAD_NAME NOT NULL
, annotationsrcid NUMBER(22,0) CONSTRAINT NN_BMAD_ANNSRCID NOT NULL
);

ALTER TABLE A2_BIOMARTARRAYDESIGN
  ADD CONSTRAINT PK_BIOMARTARRAYDESIGN
    PRIMARY KEY (BIOMARTARRAYDESIGNID)
  ENABLE;

ALTER TABLE A2_BIOMARTARRAYDESIGN
  ADD CONSTRAINT FK_BIOMARTARRAYDESIGN_AD
    FOREIGN KEY (ARRAYDESIGNID)
    REFERENCES A2_ARRAYDESIGN (ARRAYDESIGNID)
    ON DELETE CASCADE
    ENABLE;

ALTER TABLE A2_BIOMARTARRAYDESIGN
  ADD CONSTRAINT FK_BMAD_ANNSRC
    FOREIGN KEY (annotationsrcid)
    REFERENCES A2_ANNOTATIONSRC (annotationsrcid)
    ON DELETE CASCADE
    ENABLE;

ALTER TABLE A2_BIOMARTARRAYDESIGN
  ADD CONSTRAINT UQ_BMAD_ANNSRCID_NAME
    UNIQUE(annotationsrcid, NAME)
    ENABLE;

CREATE OR REPLACE TRIGGER A2_BIOMARTARRAYDESIGN_INSERT
before insert on A2_BIOMARTARRAYDESIGN
for each row
begin
if(:new.biomartarraydesignId is null) then
select A2_BIOMARTARRAYDESIGN_SEQ.nextval into :new.biomartarraydesignId from dual;
end if;
END;
/
exit;
