-- Set active to true for software which corresponds to Ensembl 61
UPDATE A2_SOFTWARE SET ISACTIVE='T' WHERE NAME='Ensembl' AND VERSION='61';


Insert into A2_SOFTWARE (NAME,VERSION,ISACTIVE) values ('metazoa','11','F');
Insert into A2_SOFTWARE (NAME,VERSION,ISACTIVE) values ('plants','11','F');
Insert into A2_SOFTWARE (NAME,VERSION,ISACTIVE) values ('Ensembl','64','F');
Insert into A2_SOFTWARE (NAME,VERSION,ISACTIVE) values ('fungi','11','F');


-- load default annotation sources
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='metazoa' AND VERSION='11'),(SELECT ORGANISMID FROM A2_ORGANISM WHERE NAME='anopheles gambiae'),'http://metazoa.ensembl.org/biomart/martservice?','agambiae_eg_gene','metazoa','anopheles_gambiae','mysql.ebi.ac.uk:4157','biomart',to_timestamp('19-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='plants' AND VERSION='11'),2,'http://plants.ensembl.org/biomart/martservice?','athaliana_eg_gene','plants','arabidopsis_thaliana','mysql.ebi.ac.uk:4157','biomart',to_timestamp('19-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='Ensembl' AND VERSION='64'),57,'http://www.ensembl.org/biomart/martservice?','xtropicalis_gene_ensembl','ensembl','xenopus_tropicalis','ensembldb.ensembl.org:5306','biomart',to_timestamp('19-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='Ensembl' AND VERSION='64'),9,'http://www.ensembl.org/biomart/martservice?','cintestinalis_gene_ensembl','ensembl','ciona_intestinalis','ensembldb.ensembl.org:5306','biomart',to_timestamp('19-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='Ensembl' AND VERSION='64'),10,'http://www.ensembl.org/biomart/martservice?','drerio_gene_ensembl','ensembl','danio_rerio','ensembldb.ensembl.org:5306','biomart',to_timestamp('26-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='Ensembl' AND VERSION='64'),11,'http://www.ensembl.org/biomart/martservice?','dmelanogaster_gene_ensembl','ensembl','drosophila_melanogaster','ensembldb.ensembl.org:5306','biomart',to_timestamp('26-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='Ensembl' AND VERSION='64'),12,'http://www.ensembl.org/biomart/martservice?','ggallus_gene_ensembl','ensembl','gallus_gallus','ensembldb.ensembl.org:5306','biomart',to_timestamp('19-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='Ensembl' AND VERSION='64'),15,'http://www.ensembl.org/biomart/martservice?','hsapiens_gene_ensembl','ensembl','homo_sapiens','ensembldb.ensembl.org:5306','biomart',to_timestamp('19-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='Ensembl' AND VERSION='64'),4,'http://www.ensembl.org/biomart/martservice?','btaurus_gene_ensembl','ensembl','bos_taurus','ensembldb.ensembl.org:5306','biomart',to_timestamp('19-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='Ensembl' AND VERSION='64'),6,'http://www.ensembl.org/biomart/martservice?','celegans_gene_ensembl','ensembl','caenorhabditis_elegans','ensembldb.ensembl.org:5306','biomart',to_timestamp('19-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='Ensembl' AND VERSION='64'),18,'http://www.ensembl.org/biomart/martservice?','mmulatta_gene_ensembl','ensembl','macaca_mulatta','ensembldb.ensembl.org:5306','biomart',to_timestamp('19-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='Ensembl' AND VERSION='64'),20,'http://www.ensembl.org/biomart/martservice?','mmusculus_gene_ensembl','ensembl','mus_musculus','ensembldb.ensembl.org:5306','biomart',to_timestamp('19-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='Ensembl' AND VERSION='64'),31,'http://www.ensembl.org/biomart/martservice?','rnorvegicus_gene_ensembl','ensembl','rattus_norvegicus','ensembldb.ensembl.org:5306','biomart',to_timestamp('26-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='Ensembl' AND VERSION='64'),33,'http://www.ensembl.org/biomart/martservice?','scerevisiae_gene_ensembl','ensembl','saccharomyces_cerevisiae','ensembldb.ensembl.org:5306','biomart',to_timestamp('19-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='fungi' AND VERSION='11'),34,'http://fungi.ensembl.org/biomart/martservice?','spombe_eg_gene','fungi','schizosaccharomyces_pombe','mysql.ebi.ac.uk:4157','biomart',to_timestamp('19-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='Ensembl' AND VERSION='64'),88,'http://www.ensembl.org/biomart/martservice?','cfamiliaris_gene_ensembl','ensembl','canis_familiaris','ensembldb.ensembl.org:5306','biomart',to_timestamp('19-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
Insert into A2_ANNOTATIONSRC (SOFTWAREID,ORGANISMID,URL,BIOMARTORGANISMNAME,DATABASENAME,MYSQLDBNAME,MYSQLDBURL,ANNSRCTYPE,LOADDATE,ISAPPLIED) values ((SELECT SOFTWAREID FROM A2_SOFTWARE WHERE NAME='Ensembl' AND VERSION='64'),112,'http://www.ensembl.org/biomart/martservice?','csavignyi_gene_ensembl','ensembl','ciona_savignyi','ensembldb.ensembl.org:5306','biomart',to_timestamp('27-OCT-11','DD-MON-RR HH.MI.SSXFF AM'),'F');
