-- Drop Views

DROP VIEW VWDESIGNELEMENTGENELINKED;

DROP VIEW VWDESIGNELEMENTGENEDIRECT;

DROP VIEW VWGENEPROPERTIES;

-- Drop MAPPINGSWID column in A2_ARRAYDESIGN table
ALTER TABLE "A2_ARRAYDESIGN" DROP CONSTRAINT FK_ARRAYDESIGN_MAPPINGSW;

ALTER TABLE "A2_ARRAYDESIGN" DROP COLUMN MAPPINGSWID;

-- Drop  A2_BIOENTITY2BIOENTITY table
DROP TRIGGER A2_BIOENTITY2BIOENTITY_INSERT;

DROP INDEX  IDX_BE2BE_FROM;

DROP INDEX IDX_BE2BE_TO;

DROP INDEX IDX_BE2BE_FROM_TO;

DROP SEQUENCE A2_BIOENTITY2BIOENTITY_SEQ;

DROP TABLE A2_BIOENTITY2BIOENTITY cascade constraints;

-- Drop  A2_BERELATIONTYPE table

DROP SEQUENCE A2_BERELATIONTYPE_SEQ;

DROP TRIGGER A2_BERELATIONTYPE_INSERT;

DROP TABLE A2_BERELATIONTYPE cascade constraints;




