DROP TRIGGER "A2_ASSAYSAMPLE_INSERT";

DROP SEQUENCE "A2_ASSAYSAMPLE_SEQ";

ALTER TABLE "A2_ASSAYSAMPLE" DROP CONSTRAINT PK_ASSAYSAMPLE;

ALTER TABLE "A2_ASSAYSAMPLE" DROP CONSTRAINT UQ_ASSAYSAMPLE;

ALTER TABLE "A2_ASSAYSAMPLE" DROP COLUMN ASSAYSAMPLEID;

ALTER TABLE "A2_ASSAYSAMPLE" 
  ADD CONSTRAINT "PK_ASSAYSAMPLE" 
    PRIMARY KEY (ASSAYID,SAMPLEID)
    /*PK_TABLESPACE*/
    ENABLE;  

CREATE OR REPLACE VIEW "VWSAMPLEASSAY" ("ASSAYID", "SAMPLEID", "ASSAYACCESSION") AS select asa.ASSAYID, asa.SAMPLEID, a.Accession AssayAccession
from a2_assaysample asa
join a2_assay a on a.AssayID = asa.AssayID;
