-- Crete A2_BIOMART_ANNSRC
CREATE TABLE  A2_BIOMART_ANNSRC(
  annotationsrcid NUMBER(22,0)  CONSTRAINT NN_BM_ANNSRC_ID NOT NULL
  , ORGANISMID NUMBER(22,0) CONSTRAINT NN_BM_ANNSRC_ORGANISM NOT NULL
  , biomartorganismname VARCHAR2(255)
  , databaseName VARCHAR2(255)
  , mySqlDbName VARCHAR2(255)
  , mySqlDbUrl VARCHAR2(255)
);

ALTER TABLE A2_BIOMART_ANNSRC
  ADD CONSTRAINT PK_BIOMART_ANNSRC
    PRIMARY KEY (annotationSrcId)
  ENABLE;

ALTER TABLE A2_BIOMART_ANNSRC
  ADD CONSTRAINT FK_BIOMART_ANNSRC_ANNSRC
    FOREIGN KEY (annotationsrcid)
    REFERENCES A2_ANNOTATIONSRC (annotationsrcid)
    ON DELETE CASCADE
    ENABLE;

ALTER TABLE A2_BIOMART_ANNSRC
  ADD CONSTRAINT FK_BIOMART_ANNSRC_ORGANISM
    FOREIGN KEY (ORGANISMID)
    REFERENCES A2_ORGANISM (ORGANISMID)
    ON DELETE CASCADE
    ENABLE;

ALTER TABLE A2_BIOMART_ANNSRC
  ADD CONSTRAINT UQ_BMANNSRC_ORG_TYPE
    UNIQUE(SOFTWAREID, ANNSRCTYPE, ORGANISMID)
    ENABLE;

--  copy biomart related values from annsrc table
INSERT INTO A2_BIOMART_ANNSRC (
  ANNOTATIONSRCID,
  ORGANISMID,
  BIOMARTORGANISMNAME,
  DATABASENAME,
  MYSQLDBNAME,
  mySqlDbUrl
 )
SELECT
  ANNOTATIONSRCID,
  ORGANISMID,
  BIOMARTORGANISMNAME,
  DATABASENAME,
  MYSQLDBNAME,
  MYSQLDBURL
FROM A2_ANNOTATIONSRC;

-- modify A2_ANNOTATIONSRC: drop  biomart related columns
ALTER TABLE A2_ANNOTATIONSRC
DROP CONSTRAINT NN_ANNOTATIONSRC_ORGANISM;

ALTER TABLE A2_ANNOTATIONSRC
DROP CONSTRAINT UQ_ANNSRC_NAME_V_ORG_TYPE;
   
ALTER TABLE A2_ANNOTATIONSRC
DROP
   (ORGANISMID,
  BIOMARTORGANISMNAME,
  DATABASENAME,
  MYSQLDBNAME,
  MYSQLDBURL);

ALTER TABLE A2_ANNOTATIONSRC
ADD NAME VARCHAR(255);

-- insert values for name
UPDATE  A2_ANNOTATIONSRC ANS
SET NAME = (
  SELECT  O.NAME || ' / ' || SW.NAME || ' v.' || SW.VERSION
  FROM A2_BIOMART_ANNSRC BMAS, A2_ORGANISM O, A2_SOFTWARE SW
  WHERE O.ORGANISMID=BMAS.ORGANISMID
  AND SW.SOFTWAREID = ANS.SOFTWAREID
  AND BMAS.ANNOTATIONSRCID = ans.ANNOTATIONSRCID
);

-- add constraints on ANNSRCNAME column
ALTER TABLE A2_ANNOTATIONSRC
  ADD CONSTRAINT UQ_ANNSRC_NAME
    UNIQUE(NAME)
    ENABLE;


-- Rename A2_BIOMARTPROPERTY table
ALTER TABLE A2_BIOMARTPROPERTY
RENAME TO A2_EXTERNAL_BEPROPERTY;

ALTER TABLE A2_EXTERNAL_BEPROPERTY
DROP CONSTRAINT PK_BMPROPERTY;

ALTER TABLE A2_EXTERNAL_BEPROPERTY RENAME COLUMN BIOMARTPROPERTYID TO EXTBEPROPERTYID;

ALTER TABLE A2_EXTERNAL_BEPROPERTY
  ADD CONSTRAINT PK_EXT_BEPROPERTY
    PRIMARY KEY (EXTBEPROPERTYID)
  ENABLE;

RENAME A2_BIOMARTPROPERTY_SEQ to A2_EXTERNAL_BEPROPERTY_SEQ;

CREATE OR REPLACE TRIGGER A2_EXTERNAL_BEPROPERTY_INSERT
before insert on A2_EXTERNAL_BEPROPERTY
for each row
begin
if(:new.EXTBEPROPERTYID is null) then
select A2_EXTERNAL_BEPROPERTY_SEQ.nextval into :new.EXTBEPROPERTYID from dual;
end if;
END;
/

ALTER TRIGGER A2_EXTERNAL_BEPROPERTY_INSERT ENABLE;

-- Rename A2_BIOMARTARRAYDESIGN table
ALTER TABLE A2_BIOMARTARRAYDESIGN
RENAME TO A2_EXTERNAL_ARRAYDESIGN;

ALTER TABLE A2_EXTERNAL_ARRAYDESIGN
DROP CONSTRAINT PK_BIOMARTARRAYDESIGN;

ALTER TABLE A2_EXTERNAL_ARRAYDESIGN RENAME COLUMN BIOMARTARRAYDESIGNID TO EXTARRAYDESIGNID;

ALTER TABLE A2_EXTERNAL_ARRAYDESIGN
  ADD CONSTRAINT PK_EXT_ARRAYDESIGN
    PRIMARY KEY (EXTARRAYDESIGNID)
  ENABLE;

RENAME A2_BIOMARTARRAYDESIGN_SEQ TO A2_EXTERNAL_ARRAYDESIGN_SEQ;

CREATE OR REPLACE TRIGGER A2_EXTERNAL_ARRAYDESIGN_INSERT
before insert on A2_EXTERNAL_ARRAYDESIGN
for each row
begin
if(:new.EXTARRAYDESIGNID is null) then
select A2_EXTERNAL_ARRAYDESIGN_SEQ.nextval into :new.EXTARRAYDESIGNID from dual;
end if;
END;
/

ALTER TRIGGER A2_EXTERNAL_ARRAYDESIGN_INSERT ENABLE;
