-- AnnotationSource table
-- CREATE SEQUENCE   A2_GENESIGANNOTATIONSRC_SEQ
--     MINVALUE 1 MAXVALUE 1.00000000000000E+27
--     INCREMENT BY 1 START WITH 1 CACHE 20
--     NOORDER  NOCYCLE;

CREATE TABLE  A2_GENESIGANNOTATIONSRC(
  annotationSrcId NUMBER(22,0)  CONSTRAINT NN_GENSIGANNSRC_ID NOT NULL
  , SOFTWAREID NUMBER(22,0)  CONSTRAINT NN_ANNOTATIONSRC_SWID NOT NULL
  , url VARCHAR2(512)
  , LOADDATE DATE
  , isApplied VARCHAR2(1) DEFAULT 'F'
);

ALTER TABLE A2_GENESIGANNOTATIONSRC
  ADD CONSTRAINT PK_GENESIGANNOTATIONSRC
    PRIMARY KEY (annotationSrcId)
  ENABLE;


ALTER TABLE A2_GENESIGANNOTATIONSRC
  ADD CONSTRAINT UQ_GSANNOTATIONSRC_SW
    UNIQUE(SOFTWAREID)
    ENABLE;

ALTER TABLE A2_GENESIGANNOTATIONSRC
  ADD CONSTRAINT "FK_GSANNSRC_SOFTWARE"
    FOREIGN KEY ("SOFTWAREID")
    REFERENCES "A2_SOFTWARE" ("SOFTWAREID")
    ON DELETE CASCADE
    ENABLE;

CREATE OR REPLACE TRIGGER A2_GENESIGANNOTATIONSRCC_INSERT
before insert on A2_GENESIGANNOTATIONSRC
for each row
begin
if(:new.annotationSrcId is null) then
select A2_ANNOTATIONSRC_SEQ.nextval into :new.annotationSrcId from dual;
end if;
END;
/