ALTER TABLE A2_ANNOTATIONSRC DROP CONSTRAINT UQ_ANNSRC_NAME;
ALTER TABLE A2_ANNOTATIONSRC ADD CONSTRAINT UQ_ANNSRC_NAME UNIQUE(NAME) ENABLE;
ALTER TABLE A2_BIOMART_ANNSRC DROP CONSTRAINT UQ_BMANNSRC_ORGANISM;
