
-- Remove old softwares from A2_DESIGNELTBIOENTITY
DROP SEQUENCE  A2_DESIGNELTBIOENTITY_SEQ;
DROP TRIGGER A2_DESIGNELTBIOENTITY_INSERT;

CREATE TABLE A2_DESIGNELTBIOENTITY_AUX PARALLEL(DEGREE 32) NOLOGGING AS
SELECT * FROM A2_DESIGNELTBIOENTITY
WHERE softwareid IN (SELECT max(softwareid) FROM A2_SOFTWARE GROUP BY NAME);

TRUNCATE TABLE A2_DESIGNELTBIOENTITY;

CREATE SEQUENCE  "A2_DESIGNELTBIOENTITY_SEQ"
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;

INSERT INTO A2_DESIGNELTBIOENTITY
SELECT A2_DESIGNELTBIOENTITY_seq.nextval, designelementid, bioentityid, softwareid from A2_DESIGNELTBIOENTITY_AUX;

CREATE OR REPLACE TRIGGER A2_DESIGNELTBIOENTITY_INSERT
before insert on A2_DESIGNELTBIOENTITY
for each row
begin
if(:new.DEBEID is null) then
select A2_DESIGNELTBIOENTITY_seq.nextval into :new.DEBEID from dual;
end if;
end;
/

ALTER TRIGGER A2_DESIGNELTBIOENTITY_INSERT ENABLE;

DROP TABLE A2_DESIGNELTBIOENTITY_AUX;

-- Remove old softwares from A2_BIOENTITYBEPV
DROP SEQUENCE A2_BIOENTITYBEPV_SEQ;
DROP TRIGGER A2_BIOENTITYBEPV_INSERT;

CREATE TABLE A2_BIOENTITYBEPV_AUX PARALLEL(DEGREE 32) NOLOGGING AS
SELECT * FROM A2_BIOENTITYBEPV
WHERE softwareid IN (SELECT max(softwareid) FROM A2_SOFTWARE GROUP BY NAME);

TRUNCATE TABLE A2_BIOENTITYBEPV;

CREATE SEQUENCE  "A2_BIOENTITYBEPV_SEQ"
    MINVALUE 1 MAXVALUE 1.00000000000000E+27
    INCREMENT BY 1 START WITH 1 CACHE 20
    NOORDER  NOCYCLE;

INSERT INTO A2_BIOENTITYBEPV
SELECT A2_BIOENTITYBEPV_SEQ.nextval, BIOENTITYID, BEPROPERTYVALUEID, SOFTWAREID from A2_BIOENTITYBEPV_AUX;

CREATE OR REPLACE TRIGGER A2_BIOENTITYBEPV_INSERT
before insert on A2_BIOENTITYBEPV
for each row
begin
if(:new.BIOENTITYBEPVID is null) then
select A2_BIOENTITYBEPV_seq.nextval into :new.BIOENTITYBEPVID from dual;
end if;
end;
/

ALTER TRIGGER A2_BIOENTITYBEPV_INSERT ENABLE;

DROP TABLE A2_BIOENTITYBEPV_AUX;

-- Remove old software from A2_SOFTWARE
DELETE FROM A2_SOFTWARE WHERE SOFTWAREID NOT IN (SELECT max(softwareid) FROM A2_SOFTWARE GROUP BY NAME);