alter table a2_software add LEGACY VARCHAR2(1) default 'F';

UPDATE A2_SOFTWARE SET LEGACY='T' WHERE NAME='miRBase' AND VERSION='14';
UPDATE A2_SOFTWARE SET LEGACY='T' WHERE NAME='Atlas' AND VERSION='Atlas';