-- Modify SOFTWARE TABLE
alter table a2_software add ISACTIVE VARCHAR2(1) default 'F';

UPDATE A2_SOFTWARE SET ISACTIVE='T' WHERE NAME='miRBase' AND VERSION='14';
UPDATE A2_SOFTWARE SET ISACTIVE='T' WHERE NAME='Atlas' AND VERSION='Atlas';
UPDATE A2_SOFTWARE SET ISACTIVE='T' WHERE NAME='fungi' AND VERSION='13';
UPDATE A2_SOFTWARE SET ISACTIVE='T' WHERE NAME='plants' AND VERSION='13';
UPDATE A2_SOFTWARE SET ISACTIVE='T' WHERE NAME='metazoa' AND VERSION='13';
UPDATE A2_SOFTWARE SET ISACTIVE='T' WHERE NAME='Ensembl' AND VERSION='66';
UPDATE A2_SOFTWARE SET ISACTIVE='T' WHERE NAME='GeneSigDB' AND VERSION='4.0';

