ALTER TABLE A2_ANNOTATIONSRC DROP CONSTRAINT UQ_ANNSRC_NAME;
ALTER TABLE A2_ANNOTATIONSRC ADD CONSTRAINT UQ_ANNSRC_NAME UNIQUE(annotationsrcid, NAME) ENABLE;
ALTER TABLE A2_BIOMART_ANNSRC DROP CONSTRAINT UQ_BMANNSRC_ORGANISM;
ALTER TABLE A2_BIOMART_ANNSRC ADD CONSTRAINT UQ_BMANNSRC_ORGANISM UNIQUE(annotationsrcid, ORGANISMID) ENABLE;