INSERT INTO A2_BIOENTITYTYPE (NAME, IDENTIFIERPROPERTYID, NAMEPROPERTYID)
VALUES ('ensprotein',
 (SELECT BEP.BIOENTITYPROPERTYID FROM A2_BIOENTITYPROPERTY BEP WHERE BEP.NAME='ensprotein'),
 (SELECT BEP.BIOENTITYPROPERTYID FROM A2_BIOENTITYPROPERTY BEP WHERE BEP.NAME='ensprotein'));