OPTIONS(ROWS=100000,DIRECT=TRUE)
load data
infile 'DataMoo/AssayPVOntology.dat'
truncate into table a2_AssayPVOntology
fields terminated by "\t" 
TRAILING NULLCOLS
(ASSAYPVONTOLOGYID 
,ONTOLOGYTERMID "get_ontologytermid(:ONTOLOGYID, :ACCESSION) "
,ASSAYPVID "get_assaypvid(:ASSAYID, :ORIG_VALUE, :ORIG_VALUE_SRC) "
,ASSAYID BOUNDFILLER
,ACCESSION BOUNDFILLER  
,ONTOLOGYID BOUNDFILLER
,ORIG_VALUE BOUNDFILLER
,ORIG_VALUE_SRC BOUNDFILLER
)

