OPTIONS(ROWS=100000,DIRECT=TRUE)
load data
infile 'DataMv/GeneGPV.dat'
truncate into table a2_GeneGPV
fields terminated by "\t" 
TRAILING NULLCOLS
(GENEGPVID
,GENEPROPERTYVALUEID "get_GenePropertyValueID(:GENEPROPERTYID, :VALUE )"
,GENEID
,GENEPROPERTYID BOUNDFILLER 
,VALUE BOUNDFILLER
)

