OPTIONS(ROWS=100000,DIRECT=TRUE)
load data
infile 'DataMv/SamplePV.dat'
truncate into table a2_SamplePVOntology
fields terminated by "\t" 
TRAILING NULLCOLS
(SAMPLEPVONTOLOGYID 
,ONTOLOGYTERMID "get_ontologytermid(:ONTOLOGYID, :ACCESSION) "
,SAMPLEPVID "get_samplepvid(:SAMPLEID, :ORIG_VALUE, :ORIG_VALUE_SRC) "
,SAMPLEID BOUNDFILLER
,ACCESSION BOUNDFILLER  
,ONTOLOGYID BOUNDFILLER
,ORIG_VALUE BOUNDFILLER
,ORIG_VALUE_SRC BOUNDFILLER
)

